src/components/Navbar/Navbar.jsx
close #12 
<br />
- `/` 위치에서도 홈메뉴가 활성화될 수 있게 Navbar 컴포넌트 내부에 있는 `getCurrentMenuColor` 함수에 조건 추가
<br />
=> #12 [FIX] /에 있을 때 하단 Navbar에서 홈메뉴가 활성화되지 않는 문제 해결

README.md
close #27 
<br />
- README.md 작성
- 리액트 리뉴얼 이유
- 역할 분담
- 현재까지 사용한 기술 스택
=> #27 [DOCS] Update README.md

src/pages/MyPage/DeleteAccountPage.jsx, src/pages/MyPage/DeleteAccountPage.module.css, src/pages/MyPage/MyPage.jsx
close #18
<br />
- 디자인 변경
<br />
|<img width="250" alt="" src="https://github.com/user-attachments/assets/dfa0dc91-c1a0-44a2-b7c8-4d300c13961e"> |
=> #18 [MODIFY] 탈퇴 페이지 UI 변경

src/components/Navbar/Navbar.module.css, src/components/Sidebar/List/List.jsx, src/components/Sidebar/Sidebar.jsx, src/components/Sidebar/Sidebar.module.css, src/constants/menus.js
close #44
<br />
- Sidebar 컴포넌트에 새로운 디자인 적용
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/19ef2c71-3927-46ba-82fe-1e21f2c42a01"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/c843358c-6441-45ba-968b-2eb7b0721a5c"> |
| 미로그인 | 로그인 |
<br />
=> #44 [STYLE] Sidebar 컴포넌트에 새로운 디자인 적용

public/index.html, src/components/Toast/Toast.jsx, src/components/Toast/Toast.module.css, src/constants/index.js, src/constants/toast.js, src/contexts/ToastContext.jsx, src/hooks/useToast.jsx, src/index.css, src/index.js
close #54
<br />
- Toast 컴포넌트 개발
- useToast 훅 개발
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/70ecb91b-7d31-472a-9b96-f3ceca077186"> |
<br />
- ToastContext.jsx의 ToastProvider에서 `toasts` 배열을 순회하며 토스트 메시지를 렌더링합니다.
- `useToast`는 인자로 전달받은 toast를 `toasts` 배열에 추가합니다. 추가된 toast가 화면에 그려집니다.
- Toast 컴포넌트가 렌더링되고 3초 후 'toasts' 배열에서 삭제합니다.
- 이미 존재하고 있는 toast를 추가하면 기존 toast를 삭제하고 새로 추가합니다.
- 화면 노출 시간이 3초 늘어납니다.
- Toast 컴포넌트가 언마운트 되기 전 opacity가 0으로 서서히 바뀐 후 언마운트됩니다.
- constants/toast.js에서 toast를 미리 정의 후 사용합니다.
<br />
=> #54 [FEAT] Toast 개발

src/index.js
close #88
<br />
- index.js 내 중복 선언되어 있는 코드 수정
<br />
=> #88 [FIX] index.js 내 중복 선언되어 있는 코드 수정

src/App.module.css, src/components/Modal/Modal.module.css, src/components/Navbar/Navbar.module.css, src/components/Sidebar/Sidebar/Sidebar.module.css, src/index.css
close #108
<br />
- App.jsx의 max-width를 600px로 수정
- Sidebar 너비 조정
- Navbar 너비 조정
- Modal 너비 조정
<br />
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/8a76e288-2fce-4e55-8849-a3e3bb0de9fa"> |
=> #108 [STYLE] PC 디스플레이 너비를 600px로 조정

src/components/InputBar/InputBar.module.css
close #114
<br />
- InputBar의 max-width를 `var(--default-width)`로 수정
<br />
| <img width="1582" alt="image" src="https://github.com/user-attachments/assets/789b72dd-f051-47f9-9769-a2091cf36d2e"> |
=> #114 [STYLE] InputBar의 max-width 수정

craco.config.js, jsconfig.json, package.json, src/components/Header/Header.jsx, src/hooks/index.js, src/hooks/useAuth.js, src/pages/BoardPage/BoardListPage/BoardListPage.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx, src/pages/MyPage/MyPage/PolicyTab.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx, yarn.lock
close #126
<br />
- 로그아웃 기능 및 useAuth 커스텀 훅 구현
- 헤더 내 로그아웃 기능 공통 모듈화 적용
- import alias 설정 및 hooks 디렉터리 구조 개선 (하단 예시 참고)
- 기존 import 문
```
import { useAuth } from '../../hooks';
import { useAuth } from '../../components';
```
- import alias 설정 후
```
import { useAuth } from '@/hooks';
import { useAuth } from '@/components';
```
<br />
=> #126 [FEAT] 로그아웃 기능 구현

package.json, yarn.lock
close #133
<br />
- craco 공식 라이브러리로 수정
<br />
=> #133 [MODIFY] craco 공식 라이브러리로 수정

src/components/Comment/Comment/Comment.jsx, src/components/Comment/CommentList/CommentList.jsx, src/components/Comment/NestedComment/NestedComment.jsx, src/components/NoticeBar/NoticeBar.jsx, src/components/PostBar/PostBar.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx
close #178
<br />
- [STYLE] 숫자값에 toLocaleString() 추가
- (기존) 8000 -> (변경후) 8,000 
<br />
=> #178 [STYLE] 숫자값에 toLocaleString() 추가

src/hooks/useScrap.jsx
close #188
<br />
- useScrap에 중복 import 제거
<br />
- useScrap에 중복 import가 있어 삭제했습니다.
=> #188 [FIX] useScrap import 중복 제거

src/components/Comment/Comment/Comment.jsx, src/components/Comment/Comment/Comment.module.css, src/components/Comment/NestedComment/NestedComment.jsx, src/components/PostBar/PostBar.jsx, src/pages/BoardPage/BoardListPage/BoardListPage.jsx, src/pages/PostPage/PostEditPage/PostEditPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx, src/utils/formattedNowTime.js, src/utils/timeAgo.js
close #198
<br />
- isDeleted인 댓글의 대댓글 및 좋아요 아이콘 숨김
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/45658129-611d-4109-8119-61ebe9c76e15"> |
| 삭제된 댓글의 대댓글, 좋아요 아이콘 숨김 |
=> #198 [MODIFY] 삭제된 댓글의 대댓글, 좋아요 아이콘 숨김

src/components/DropDownBlue/DropDownBlue.jsx, src/components/DropDownBlue/DropDownBlue.module.css, src/constants/dropDown.js, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
close #202
<br />
- 한 개의 토글만 열 수 있도록 수정
- 연도는 최근순으로 정렬
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/64a0a82d-60df-474f-965e-10c8c50e84e1"> |
| 연도 최근순 정렬 |
=> #202 [MODIFY] 시험후기 필터

src/apis/point.js, src/components/Calendar/Calendar.jsx, src/components/Calendar/Tile/Tile.jsx, src/components/Calendar/Tile/Tile.module.css, src/components/Toast/Toast.module.css, src/constants/toast.js, src/pages/AttendancePage/AttendancePage.jsx
close #204
<br />
- 출석체크 API 연결
- 월별 출석 이력 조회 API 연결
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/73a494de-624c-47bd-92c6-92fd95772039"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/ee8153ea-1813-4356-af6f-1ec4f49384d9"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/7fbe4997-0b25-46fe-9703-d06e775f9e3b"> |
| :---------------------: | :---------------------: | :---------------------: |
| 출석체크 완료 `userId = 17` | 하루에 한 번 출석 가능 `userId = 62` | 월별 출석 이력 조회 `userId = 62 (더미)` |
=> #204 [FEAT] 출석체크 관련 API 연결

yarn.lock
=> #225 [FEAT] yarn.lock 파일 재설치 (4.1.1 ver)

package.json
close #231
<br />
- (코드, 테스트 등 변경 사항과 변경 이유를 작성해주세요.)
<br />
| (스크린샷을 넣어주세요) |
<br />
=> #231 [FIX] package.json packageManager 삭제 (빌드 오류)

.gitignore, src/axios/index.js
close #237
<br />
- 서버 도메인 수정하고, 환경변수로 분리했습니다.
<br />
- `.env` 파일 생성하고 `REACT_APP_SERVER_DOMAIN` 이름으로 서버 도메인 추가해주세요
=> #237 [FEAT] 서버 도메인 변경 및 환경변수로 분리

src/apis/login.js, src/components/InputBar/InputBar.jsx, src/components/ReviewDownload/ReviewDownload.jsx, src/dummy/data/user.js, src/hooks/useComment.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #240
<br />
- 배포 환경에서 mixed-content 에러 발생해서 도메인 수정했습니다.
=> #240 [FIX] 로그인 요청 api의 서버 도메인을 환경변수로 교체

src/apis/banner.js, src/apis/index.js, src/components/Carousel/Carousel/Carousel.jsx, src/components/Carousel/Slide/Slide.jsx, src/components/Carousel/Slide/Slide.module.css, src/pages/MainPage/MainPage.jsx
close #242
<br />
- 배너 이미지 조회 API 연결
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/9e560f03-2c48-4ffb-8513-e39bd5cf5403"> |
| 배너 조회 API 연결한 홈화면|
=> #242 [FEAT] 배너 이미지 조회 API 연결

public/index.html, src/pages/AttendancePage/AttendancePage.jsx
close #246
<br />
- 구글 애드센스 연결
=> #246 [FEAT] 구글 애드센스 연결

src/axios/index.js
close #245
<br />
- authAxios 인스턴스에 타임아웃 시간 전역으로 설정
=> #245 [FEAT] axios 타이아웃 시간 전역으로 설정

src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #251
<br />
- 내가 쓴 공지가 아니면 dot3버튼을 아예 안 보이게 하여 신고모달이 안 뜨게 처리 (공지글은 신고할 수 없도록)
- 내가 쓴 공지면 dot3버튼을 보이게 하여 수정/삭제 할 수 있도록 처리
- 게시글 작성 부분에 USER.role 더미 데이터 연결
<br />
| <img width="615" alt="image" src="https://github.com/user-attachments/assets/d9a6027c-3fdc-4bd2-86e3-6b6fc88aad42"> |
| 다른 사람이 쓴 공지글에는 dot3 버튼이 아예 안 보임 |
=> #251 [STYLE] 내가 쓴 공지가 아니면, 공지글에 dot3 버튼 안 띄우도록

src/components/Comment/CommentList/CommentList.jsx, src/components/InputBar/InputBar.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/utils/filterComment.js
close #257
<br />
- 댓글 모든 케이스 적용되도록 필터링 로직 수정 (isVisible 고려, 대댓글 고려)
- 댓글 수 오류 수정 (length 계산 -> commentCount 받아오는 거로 수정)
- +) InputBar 줄바꿈 오류 수정 (코드 1줄 수정)
<br />
https://github.com/user-attachments/assets/b683e9d8-4e52-49bc-8fd7-9c70df3b8796
=> #257 [FIX] 댓글 필터링 로직 수정 & 댓글 수 오류 해결 

src/components/AppBar/CloseAppBar/CloseAppBar.module.css, src/components/Comment/Comment/Comment.module.css, src/components/DropDownMenu/DropDownMenu.module.css, src/components/NoticeBar/NoticeBar.module.css, src/components/PostBar/PostBar.module.css, src/pages/BoardPage/BoardListPage/BoardListPage.module.css, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css, src/pages/PostPage/PostPage/PostPage.module.css, src/pages/PostPage/PostWritePage/PostWritePage.module.css
close #264
<br />
- 버튼에 cursor:pointer 설정
- 게시글의 comment아이콘(단순 댓글 수 보여주기 용)에는 hover 액션 안 되도록 설정
<br />
(cursor 작동하는 건 캡쳐가 안 되는 관계로 사진 생략
<br />
=> #264 [FEAT] 버튼에 cursor:pointer 설정 & 게시글 댓글 아이콘에는 hover 액션 안 되도록 설정

src/components/PostBar/PostBar.jsx
close #262
<br />
- 전체 게시판 검색에서 PostBar 클릭 시 nav 안 되는 오류 수정
- : 게시판이 'all'인 경우를 추가하여 예외 처리
<br />
| <img width="1512" alt="스크린샷 2024-09-01 오후 8 56 22" src="https://github.com/user-attachments/assets/e8a75689-772f-4610-b3d6-1c93ab8c4df4"> | <img width="1512" alt="스크린샷 2024-09-01 오후 8 56 54" src="https://github.com/user-attachments/assets/99abd8ac-1056-4f43-93e5-42da60a5c46d"> |
| 수정 전 - all이라는 게시판 못 찾아서 에러 | 수정 후 - 정상 작동
<br />
=> #262 [FIX] 전체 게시판 검색에서 PostBar 클릭 시 nav 안 되는 오류 수정

src/components/Comment/Comment/Comment.jsx, src/components/Comment/Comment/Comment.module.css, src/components/Comment/NestedComment/NestedComment.jsx, src/components/InputBar/InputBar.jsx, src/components/Modal/DeleteModal.jsx, src/components/Modal/Options.jsx, src/contexts/CommentContext.jsx
close #261
<br />
- 내가 작성한 댓글은 수정/삭제 모달, 다른 사람이 작성한 댓글은 신고 모달 보이게 변경
=> #261 [MODIFY] 내가 작성한 댓글은 수정/삭제 모달, 다른 사람이 작성한 댓글은 신고 모달 보이게 변경

src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css
close #270 
<br />
- isWriter에 따라 수정/삭제 또는 신고 모달이 보여지게 수정
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/87b50b5c-b7e6-4ac8-82b9-da4ca2fc3138"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/caee287b-a2f6-4680-bf57-741cdbfa54d4"> |
| 내가 작성한 시험후기 | 다른 사람이 작성한 시험 후기 |
<br />
=> #270 [MODIFY] 시험후기 상세에서 isWriter에 따라 수정/삭제 또는 신고 모달이 보여지게 수정

src/apis/login.js, src/constants/toast.js, src/hooks/useAuth.js, src/pages/LoginPage/LoginPage/LoginPage.jsx
close #273
<br />
- 에러 메세지를 Toast로 바꿨습니다
<br />
<br />
- 다음 커밋에는 axios랑 hook를 정확히 구분하는 refactor을 할 것입니다.
<br />
=> #273 [FIX] Change Error Message to Toast

src/apis/banner.js, src/apis/comment.js, src/apis/examReview.js, src/apis/like.js, src/apis/login.js, src/apis/notice.js, src/apis/point.js, src/apis/post.js, src/apis/search.js, src/apis/userInfo.js, src/axios/index.js, src/components/ReviewDownload/ReviewDownload.jsx, src/constants/examReview.js, src/constants/index.js, src/constants/toast.js, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
close #281
<br />
- 포인트 증감에 대한 책임이 서버로 이관되어서 프론트에서 관리하던 시험후기 쪽 포인트 증감 로직을 삭제했습니다.
- 타임아웃 발생 시 axios가 `undefined`를 반환하는데, 이때 `undefined`에 접근하는 로직으로 인해 참조 오류가 발생해서 옵셔널 체이닝으로 오류 방어했습니다.
=> #281 [MODIFY] 시험후기 생성, 삭제 후 포인트 증감 로직 삭제

src/App.jsx, src/index.js, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/LoginPage/index.js, src/pages/MyPage/index.js, src/pages/NotFoundPage/NotFoundPage.jsx, src/pages/NotFoundPage/NotFoundPage.module.css, src/pages/NotFoundPage/index.js, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/SnoroseVerifyPage/Button/Button.jsx, src/route.js, src/utils/findRoute.js
close #277
<br />
- 요청한 리소스가 존재하지 않을 때 NotFoundPage가 보여지게 수정했습니다.
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/0c3a1efe-d710-46f8-8232-d3381a3c8ad9"> |
| NotFoundPage |
<br />
=> #277 [FEAT] 404 라우트 에러 핸들링

src/hooks/useComment.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #284
<br />
<br />
<br />
: 서버 오류 떄문에 아직 테스트는 못했습니다! 테스트 완료되는 대로 리뷰 남겨주시면 감사하겠습니다!
=> #284 [MODIFY] 게시글, 댓글 쪽 포인트 로직 삭제

src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
close #292
<br />
- `/v1/users/certifyUser` api의 요청 서버 도메인 수정
<br />
| (스크린샷을 넣어주세요) |
<br />
=> #292 [FIX] 회원가입 이메일 인증 (차단됨:mixed-content) 오류 해결

src/components/Calendar/Calendar.jsx, src/components/Calendar/Tile/Tile.jsx, src/components/Loading/FetchLoading.module.css, src/hooks/useInfiniteScroll.jsx, src/pages/AttendancePage/AttendancePage.jsx, src/pages/AttendancePage/AttendancePage.module.css, src/pages/BoardPage/BoardListPage/BoardListPage.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css, src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx, src/pages/MyPage/ActivityPage/CommentPage.jsx, src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx, src/pages/MyPage/ActivityPage/MyPostPage.jsx, src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx, src/pages/MyPage/ActivityPage/ScrapPage.jsx, src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostSearchPage/PostSearchPage.jsx, src/route.js, src/utils/findRoute.js
close #303
<br />
- useInfiniteScroll에서 hasNext가 true면 다음 페이지를 가져오지 않도록 로직 수정
<br />
<br />
=> #303 [MODIFY] useInfiniteScroll에서 hasNext로 마지막 페이지 확인

src/ProtectedRoute.jsx, src/apis/banner.js, src/components/BoardCard/BoardCard.jsx, src/components/CategoryBoard/CategoryBoardItem/CategoryBoardItem.jsx, src/components/CategoryBoard/CategoryBoardItemDetail/CategoryBoardItemDetail.jsx, src/components/MainPageListItem/MainPageListItem.jsx, src/components/ReviewDownload/ReviewDownload.jsx, src/constants/index.js, src/constants/user.js, src/pages/AttendancePage/AttendancePage.jsx, src/pages/AuthPage/AuthPage.jsx, src/pages/AuthPage/index.js, src/pages/HelpPage/HelpPage.jsx, src/pages/HelpPage/index.js, src/pages/PostPage/PostWritePage/PostWritePage.jsx, src/route.js
close #310
<br />
- 더미로 작성했던 유저 데이터를 서버에서 가져온 데이터로 교체했습니다. 
<br />
- 유저 권한에 따른 페이지 접근 제한이 제대로 적용되지 않는 문제가 있었습니다.
- 유저 roleId가 더미로 되어 있어 발생한 문제였습니다.
- 유저 roleId를 서버 데이터로 교체해서 지금은 제대로 동작합니다.
<br />
=> #310 [FEAT] 유저 더미 데이터를 서버 데이터로 교체

src/hooks/useAuth.js
close #318
<br />
- useAuth에서 로그아웃 시 데이터 갱신을 위해 `refetch`를 호출하도록 수정했습니다.
<br />
=> #318 [FIX] 홈 화면에서 로그아웃 버튼 클릭 시 버튼 텍스트가 로그인으로 바뀌도록 수정함

src/components/ReviewDownload/ReviewDownload.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
close #339
<br />
- 이미 다운로드 했거나 내가 작성한 시험후기는 다운로드 확인 모달창이 뜨지 않도록 수정했습니다.
<br />
=> #339 [FIX] 내가 작성했거나 이미 다운로드 받은 후기는 다운로드 확인 모달창을 띄우지 않음

src/hooks/useAuth.js, src/pages/MyPage/MyPage/MyPage.jsx, src/route.js
close #348
<br />
- ProtectedRoute로 권한에 따른 접근 제한 핸들링
<br />
=> #348 [REFACTOR] 마이페이지 접근 권한 핸들링 로직을 ProtectedRoute로 교체

src/components/Fieldset/TextField/TextField.jsx, src/components/Fieldset/TextField/TextField.module.css, src/components/Fieldset/index.js, src/constants/dropDown.js, src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx, src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx, src/utils/index.js, src/utils/regex.js
close #350
<br />
- 시험후기 수강 분반 입력 필드를 텍스트 필드로 변경
- 숫자만 입력되게 구현
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/9250dc09-d60d-4d5e-a8cb-a6675b1cbfe2"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/af432312-9160-400c-91e8-dd20b5b0d886"> |
| 시험후기 작성 | 시험후기 수정 |
<br />
=> #350 [MODIFY] 시험후기 수강 분반 입력 필드를 텍스트 필드로 변경

src/components/Fieldset/Dropdown/Dropdown.jsx, src/components/Fieldset/Dropdown/Dropdown.module.css, src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
close #354
<br />
- 드롭다운 메뉴 포커스 컬러 변경
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/159d6f95-a038-4035-84d6-0158192be3e1"> |
| 회원가입 - 사용자 정보 입력 화면 |
<br />
=> #352 [MODIFY] Dropdown 컴포넌트 포커스 상태인 경우 글자색 파란색으로 변경

src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx, src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx, src/utils/index.js, src/utils/regex.js, src/utils/validate.js
close #369
<br />
- 수강 분반 입력 필드 숫자만 입력 가능
- 최대 3자리까지 입력 가능
<br />
=> #369 [FIX] 수강후기 작성 - 수강 분반 입력 필드에 조건 검사 추가

src/components/Card/Card.module.css, src/constants/boardMenus.js, src/pages/NoticeListPage/NoticeListPage.jsx, src/pages/NoticeListPage/NoticeListPage.module.css, src/pages/PostPage/PostEditPage/PostEditPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx, src/route.js
close #334
<br />
- 공지사항 게시판 추가 (공지글 조회 / 작성 / 수정)
- 메인 화면에서 공지글 길어질 때 넘치지 않도록
=> #334 [FEAT] 메인페이지의 공지사항 게시판 추가 (조회/작성/수정)

src/components/PTR/PTR.jsx, src/components/PTR/PTR.module.css, src/hooks/usePagination.jsx, src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
close #389
<br />
- PTR 라이브러리 -> PTR 로직 직접 구현으로, 마우스 모션에 따라 달라지는 로딩 오류 해결
- 스크롤한 모든 페이지 refetch해오는 오류 해결 (맨 첫 페이지만 가져오도록)
=> #389 [FIX] PTR 무한 로딩 & 모든 페이지 refetch 오류 해결

src/pages/MyPage/ActivityPage/CommentPage.jsx, src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx, src/pages/MyPage/ActivityPage/MyPostPage.jsx, src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx, src/pages/MyPage/ActivityPage/ScrapPage.jsx
close #403
<br />
- 에러메세지를 화면에서 띄워주기 (알파테스트 이슈 반영)
<br />
| 다운받은 시험후기 보기 |
| <img width="250" src="https://github.com/user-attachments/assets/956baa0a-4b9d-4c7f-a1f1-db28662ad4b6" />|
<br />
=> #403 [FIX] 에러메세지를 화면에서 띄워주기(알파테스트 이슈 반영)

src/constants/point.js
close #405
<br />
- 누락된 POINT_DEDUCTION_ETC enum값 추가
=> #405 [FEAT] 누락된 POINT_DEDUCTION_ETC enum값 추가

src/apis/userInfo.js, src/components/ReviewDownload/ReviewDownload.jsx, src/hooks/useAuth.js, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/MyPage/MyPage/MyPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx
close #410
<br />
- 시험후기 다운으로 차감된 포인트를 myPageUserInfo 캐시에 실시간으로 반영
<br />
- 이전 PR에서 변경된 DeleteModal의 prop 이름이 제대로 반영되지 않아, 모달이 제대로 닫히지 않는 문제 발생
- DeleteModal이 사용되는 곳에 변경된 prop 이름을 제대로 반영해서 해결
<br />
=> #410 [FIX] 시험후기 다운로드 후 마이페이지에 포인트 차감 반영이 안 되는 문제 해결

src/components/PTR/PTR.jsx
=> #415 [FIX] PTR 드래그 잘 안 되는 오류 해결

src/apis/signUp.js, src/components/Input/Input/Input.jsx, src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindIdPage/inputCheck.js, src/pages/LoginPage/FindPwPage/FindPwPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.module.css, src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
close #430
<br />
- Input 컴포넌트에 onBlur시 trim()하게 만들기
- FindPwPage의 토스트 제가
- 이름 입력란에 공백 불허하기
=> #430 [FIX] Input 컴포넌트에 trim추가, FindPwPage의 토스트 제거, 이름에 공백 불허하기

src/apis/login.js, src/constants/toast.js
close #432
<br />
- 로그인시 id또는 pw를 미입력하면 별도의 토스트 띄우기
- 누락된 필드가 존재하면 “{필드명}을(를) 입력해주세요” 토스트 띄우기
<br />
=> #432 [FIX] 로그인시 id또는 pw를 미입력하면 별도의 토스트 띄우기

src/pages/LoginPage/FindIdPage/inputCheck.js, src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
close #436
<br />
- 닉네임 2자이상 20자 이하로 제한걸기
- 비밀번호 15자 이하 조건 추가
<br />
<br />
=> #436 [FIX] 닉네임 제약조건 추가

src/pages/LoginPage/FindIdPage/inputCheck.js, src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx
close #438
<br />
- 이름 길이 제약을 추가
- 비밀번호 길이 제약 수정
<br />
=> #438 [FIX] 회원가입 제약 조건 추가

src/components/PTR/PTR.jsx
=> #441 [FIX] PTR 스크롤 오류 고치기 전까지 테스트 위해 이전 코드로 돌리기

src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
close #460
<br />
- padStart로 두 자리 숫자로 표기하되 빈 자리는 0으로 채움
<br />
=> #460 [MODIFY] 시험후기 상세에서 수강 연도를 두 자리수 숫자로 표기

src/components/AppBar/CloseAppBar/CloseAppBar.jsx, src/components/Modal/Modal.module.css, src/constants/modalOptions.js, src/pages/PostPage/PostEditPage/PostEditPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #450 
<br />
- 리자 아닌 유저가 게시글 수정할 때 공지글 선택 옵션 보이는 오류 수정
- 게시글 작성 후 게시글 상세 페이지로 바로 이동하도록
- 글 작성 중 X버튼 누를 경우 방어 모달 띄우기
- 글 수정 중 X버튼 누를 경우 방어 모달 띄우기
| <img width="619" alt="스크린샷 2024-09-21 오후 9 00 29" src="https://github.com/user-attachments/assets/5361e5c3-2c1c-43b3-a99c-483ceb86f2ce"> | <img width="616" alt="스크린샷 2024-09-21 오후 9 00 55" src="https://github.com/user-attachments/assets/5c9af99f-540a-40d2-8f1b-188b0dbcb72a"> |
=> #450 [FIX] 리자 아닌 유저가 게시글 수정할 때 공지글 선택 옵션 보이는 오류 수정 & 방어 모달

src/components/Navbar/Navbar.jsx
close #470
<br />
- Navbar의 활성화 여부를 알 수 있는 isActive 함수 추가
- isActive 함수에 홈과 시험후기 페이지에 대힌 조건식 추가
<br />
=> #470 [FIX] 시험후기 검색에서 Navbar의 강조가 풀리는 버그 수정

src/components/Comment/Comment/Comment.module.css, src/components/InputBar/InputBar.jsx, src/contexts/CommentContext.jsx
close #472
<br />
- Enter 눌렀을 때 줄바꿈, ctrl+Enter 눌렀을 때 전송으로 키 수정
- 댓글 글자수 1000자 제한
- 대댓글 쓸 부모댓글 배경색 파란색으로 유지하기
=> #472 [FIX] 게시글 & 댓글의 input 관련 오류 해결

src/apis/comment.js, src/apis/post.js, src/pages/PostPage/PostPage/PostPage.jsx
close #391
<br />
- 댓글, 게시글 신고 path 변경사항 적용
- 게시글, 유저 신고 모달에서 옵션 선택이 안되는 문제 해결
<br />
- UI 동일
=> #391 [FIX] 기존 신고하기 API 및 모달 일부 수정

package-lock.json, src/ProtectedRoute.jsx, src/constants/role.js, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx, src/route.js
close #480
<br />
- 강등 회원(blacklist) 등급 추가
- 마이페이지 쪽에 누락된 ProtectedRoute 씌우기
<br />
=> #480 [MODIFY] 강등 회원(blacklist) 등급 추가

src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx
close #326
<br />
- 시험후기 신고 API 연동 (userId가 게시글 조회 API 스펙에 없어서, 해당 부분은 기능 미작동)
=> #326 [FEAT] 시험후기 신고 API 연동

src/constants/modalOptions.js
close #491
<br />
- 사용자 신고 코드 임시 주석 처리 (베타테스트를 위한)
- server에서 해당 기능 구현 완료시 client 작업 재개 예정 
<br />
=> #491 [FIX] 사용자 신고 코드 임시 주석 처리 (베타테스트를 위한)

src/components/Fieldset/Fieldset/Fieldset.jsx, src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
close #493
<br />
- Fieldset의 input 요소에 value 속성을 checked로 수정
- isPF, isOnline을 보여주는 컴포넌트의 prop에서 value를 checked로 수정
- 시험후기 상세에서 P/F와 온라인 수업에 대한 항목 라벨을 수정
<br />
=> #493 [FIX] 시험후기 수정 화면에서 체크박스에 대한 비제어 컴포넌트 버그 수정

src/apis/login.js, src/apis/signUp.js, src/components/Input/Input/Input.jsx, src/pages/LoginPage/FindIdPage/inputCheck.js, src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx
close #502
<br />
- 버튼을 눌러야지 인증번호 확인 가능하게 바꾸기
<br />
넘어감
=> #502 [FIX] 회원가입에 이메일 인증 로직 바꾸기

src/components/Comment/Comment/Comment.jsx, src/components/Modal/DeleteModal.jsx, src/components/ReviewDownload/ReviewDownload.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/PostPage/PostEditPage/PostEditPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #507
<br />
- DeleteModal 닫기 함수명 closeFn으로 수정하여 다른 모달들과 이름 통일
=> #507 [FIX] DeleteModal 닫기 함수명 closeFn으로 수정하여 다른 모달들과 이름 통일

src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.jsx
close #508
<br />
-android에서 가상 키보드에 '다음' 누르면 넘어가는 에러 수정
<br />
=> #508 [FIX] android에서 가상 키보드에 '다음' 누르면 넘어가는 에러 수정

src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.jsx
close #508
<br />
- e.preventDefault() 추가해줌
<br />
=> #508 [FIX] e.preventDefault()추가하기

src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
close #520
<br />
- 비밀번호 유효성 검사에 띄어쓰기 금지 내용 추가
- 오류 메세지에 띄어쓰기 내용 추가
<br />
|  <img width="250" src="https://github.com/user-attachments/assets/a84b7e7e-e567-49e9-96a7-1caba0ed6ec4" />   |
| 비밀번호 변경 페이지 |
<br />
=> #520 [FEAT] 비밀번호 유효성 검사에 띄어쓰기 금지 내용 추가

src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx, src/route.js
close #524
<br />
- 숙명인 인증 아이디 인풋의 라벨 및 placeholder 수정
- 숙명인 인증 비밀번호 인풋의 라벨 수정
<br />
| <img width="325" alt="image" src="https://github.com/user-attachments/assets/81d8d87e-adb8-48a4-ab2f-63939df4c786"> | <img width="325" alt="image" src="https://github.com/user-attachments/assets/38064251-cd58-48eb-aa83-653e5717b14c"> |
| 수정 전 숙명인 인증 페이지 | 수정 후 숙명인 인증 페이지 |
<br />
=> #524 [MODIFY] 숙명인 인증 인풋 라벨 수정

src/axios/index.js
close #528
<br />
- authAxios 타임아웃 설정 삭제
<br />
=> #528 [MODIFY] authAxios 타임아웃 설정 삭제

src/components/ReviewDownload/ReviewDownload.jsx, src/components/ReviewDownload/ReviewDownload.module.css
close #531
<br />
- ReviewDownload 컴포넌트 max-width 지정
<br />
| <img width="325" alt="image" src="https://github.com/user-attachments/assets/f6aa0c78-3eac-4fe2-b833-e976e4b36003"> | <img width="325" alt="image" src="https://github.com/user-attachments/assets/b77c7b44-5370-4cd3-8580-8d9a0ab22e98"> |
<br />
=> #531 [FIX] ReviewDownload 컴포넌트 max-width 지정

src/pages/AttendancePage/AttendancePage.jsx, src/pages/AttendancePage/AttendancePage.module.css
close #531
<br />
- loading state 추가
- api 호출 로직에 loading set 추가
- loading이 true일 때 로딩 UI 노출
<br />
| <img width="325" alt="image" src="https://github.com/user-attachments/assets/fc333bf5-9758-4472-9a5f-fc62808dac7d"> |
| 로딩 중일 때 로딩 UI 노출 |
<br />
=> #531 [FIX] 출석체크 시 로딩 상태일 때 로딩 UI 노출

src/pages/AttendancePage/AttendancePage.module.css
close #534
<br />
- 출석페이지 상단 패딩 삭제
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/6cb56d36-83c3-4ddc-847d-438d5f142d72"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/a95dfe6f-a84b-429b-bada-9fb15c063729"> |
<br />
=> #534 [STYLE] 출석페이지 상단 패딩 삭제

public/index.html
close #544
<br />
- input 태그를 focus시, zoom-in 되는 문제 해결
<br />
| <img width="250" src="https://github.com/user-attachments/assets/b4a69d5c-9262-4f88-8cdb-2c874c095a98" /> | <img width="250" src="https://github.com/user-attachments/assets/d1e89a91-4af9-4a19-a685-e7b20ae991b3" /> |
| :---------------------: |  :---------------------: |
| 이전 문제 화면 | 해결 화면 |
<br />
=> #544 [FIX] input 태그를 focus시, zoom-in 되는 문제 해결

src/components/AppBar/AppBar/AppBar.module.css, src/components/AppBar/BackAppBar/BackAppBar.module.css, src/components/AppBar/CloseAppBar/CloseAppBar.module.css
close #546
<br />
- AppBar, CloseAppBar, BackAppBar의 z-index를 1로 설정
<br />
=> #546 [FIX] 앱바의 z-index 1로 수정

src/hooks/useSearch.jsx, src/pages/BoardPage/BoardPage/BoardPage.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx, src/pages/PostPage/PostSearchPage/PostSearchPage.jsx, src/route.js
close #548
<br />
- 검색 키워드를 pathParam이 아니라 queryParam으로 수정
<br />
=> #548 [FIX] uri에서 .(dot)을 자동으로 제거해서 검색이 안 되는 문제 수정

src/route.js
close #553
<br />
- NotFoundPage 라우트 주석 되돌리기
<br />
=> #553 [FIX] NotFoundPage 라우트 주석 되돌리기

src/route.js
close #558
<br />
- route.js 주석 처리한 것 되돌리기
- main에 머지하기 위해 임시로 해놨던 주석을 원래대로 되돌렸습니다.
<br />
=> #558 [CHORE] route.js 주석 되돌리기

src/route.js
close #564
<br />
- route.js에서 `<App />`의 `hideNav` 속성 삭제
<br />
=> #564 [FIX] 루트 경로에서 Navbar가 보이지 않는 문제 수정

src/hooks/useAuth.js, src/hooks/useComment.jsx, src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx, src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #566
<br />
- 새로고침을 해야만 포인트가 업데이트되는 이슈 해결
<br />
- UI 변경 사항 없음
=> #566 [FIX] 새로고침을 해야만 포인트가 업데이트되는 이슈 해결

src/constants/modalOptions.js, src/pages/PostPage/PostPage/PostPage.jsx
close #568
<br />
- 유저 신고 기능 구현
<br />
| <img width='250' src='https://github.com/user-attachments/assets/acd27e1c-ffc2-4cee-815a-4aaf9fa4a179' /> | <img width='250' src='https://github.com/user-attachments/assets/d8275922-2984-49d9-85d6-3c2375ab2f5c' /> |
| 게시글 내 `신고` 모달 |  게시글 내 `유저 신고` 상세 옵션 |
<br />
=> #568 [FEAT] 유저 신고 기능 구현

src/route.js
close #575
<br />
- UnderConstructionPage와 NotFoundPage 페이지 제외 모든 라우트 주석
<br />
=> #575 [CHORE] 운영 브랜치에서 사용할 라우트로 수정

src/pages/BoardPage/BoardListPage/BoardListPage.jsx, src/pages/BoardPage/BoardListPage/BoardListPage.module.css, src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx, src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.module.css, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #580
<br />
- 게시글 리스트를 컴포넌트로 분리
- 게시글 작성 및 삭제 시 post에 대한 쿼리 삭제
<br />
=> #580 [REFACTOR] 게시글 리스트 컴포넌트로 분리

src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
close #582
<br />
- 시험후기 삭제 후 post에 대한 캐시 삭제
<br />
=> #582 [MODIFY] 시험후기 삭제 후 리스트 페이지에서 FetchLoading 노출

src/pages/AttendancePage/AttendancePage.module.css
close #584
<br />
- FetchLoading 위치 가운데로 정렬
<br />
=> #584 [STYLE] 출석체크 FetchLoading 가운데로 정렬

src/index.css
close #586
<br />
- body의 overflow를 hidden으로 설정
=> #586 [STYLE] body의 overflow를 hidden으로 설정

src/index.css
close #588 
<br />
- body의 padding을 0으로 강제
<br />
=> #588 [STYLE] body의 padding을 0으로 강제

src/pages/NoticeListPage/NoticeListPage.jsx, src/pages/PostPage/PostEditPage/PostEditPage.jsx, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostWritePage/PostWritePage.jsx
close #597
<br />
- 공지글 상세페이지로 nav 안 되는 오류 해결 (CloseAppBar의 속성값이 바뀌어 생긴 오류였음)
- 공지글 등록 안 되는 오류 해결 (isNotice가 계속 false로 들어가고 있었음)
- 게시글 작성/수정에 replace 적용
=> #597 [FIX] 공지글 상세페이지로 nav 안 되는 오류, 공지글 등록 안 되는 오류, 게시글 작성/수정에 replace 적용

src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
close #570
<br />
- 닉네임 내 독립적인 자음 허용하도록 유효성 검사 수정
<br />
| <img width='250' src='https://github.com/user-attachments/assets/9913ca65-bcb7-47d9-9d73-6ac8c16f7641' /> | <img width='250' src='https://github.com/user-attachments/assets/bb9df9a7-8325-4141-9a6f-64ded8a54287' /> |
<br />
=> #570 [MODIFY] 닉네임 내 독립적인 자음 허용하도록 유효성 검사 수정

src/components/BoardCard/BoardCard.module.css
close #614
<br />
- BoardCard padding 수정
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/a7da74c1-2676-4230-9dc4-5dd6179843c6"> |
| BoardCard `padding` 수정 |
<br />
=> #614 [STYLE] BoardCard padding 수정

src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx
close #622
<br />
- 시험후기 작성 성공하면 상세 페이지로 리다이렉트
<br />
=> #622 [MODIFY] 시험후기 작성 후 상세 페이지로 이동

src/components/Accordion/AccordionListItem.jsx, src/constants/about.js, src/pages/AboutPage/AboutPage.jsx
close #624
<br />
- About 스노로즈에서 map에 누락된 key 추가
<br />
=> #624 [CHORE] About 스노로즈에 누락되었던 map key 추가

package-lock.json, src/apis/login.js, src/axios/index.js, src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindIdPage/inputCheck.js, src/pages/LoginPage/FindPwPage/FindPwPage.jsx, src/pages/LoginPage/FoundIdPage/FoundIdPage.jsx, src/pages/LoginPage/FoundIdPage/FoundIdPage.module.css, src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
close #627
<br />
- 로그인 페이지에 제약 조건을 수정 (FindPw에 아이디 입력란 조건 제거)
- 회원가입에서 닉네임 초성 가능하게 조건 수정 (ex. ㄱㄴㄷ를 닉네임으로 지정 가능)
- 아이디찾기 로직이 바뀌어 (아이디 찾기 성공 시 바로 화면에 id가 보여지는 것이 아닌, 메일로 id가 전달되는 방식)
- 아이디찾기 페이지의 화면 구성을 바꿈
- 아이디, 비밀번호 찾기 placeholder문구 통일
<br />
=> #627 [FIX] 제약조건 수정 & 아이디 찾기 페이지 로직 수정

src/components/Route/CheckExamPeriodRoute.jsx, src/route.js
close #632
<br />
- 시험후기 작성 기간이 아닐 경우 메인으로 리다이렉트 할 수 있게 CheckExamPeriodRoute 적용했습니다.
<br />
=> #632 [FEAT] 시험후기 시험기간이 아닌 경우 메인으로 리다이렉트

src/components/NoticeBar/NoticeBar.jsx
close #650
<br />
- NoticeBar에서 createAt 변환을 dateFormat으로 변경
<br />
=> #650 [MODIFY] NoticeBar에서 createAt 변환을 dateFormat으로 변경

src/ProtectedRoute.jsx
close #652
<br />
- ProtectedRoute에서 userInfo가 undefined인 경우 return
- 임시 조치입니다!
=> #652 [CHORE] ProtectedRoute에서 userInfo가 undefined인 경우 return

src/constants/boardMenus.js, src/index.css, src/pages/NoticeListPage/NoticeListPage.jsx, src/route.js
close #694
<br />
- 시험후기 공지글 nav 404 에러 해결
- 텍스트 드래그 방지 처리
=> #649 [FIX] 시험후기 공지글 nav 404 에러 해결 & 텍스트 드래그 방지 처리

src/components/Footer/Footer.jsx, src/components/Footer/Footer.module.css
close #517
<br />
- email 수정
<br />
=> #517 [MODIFY] email 수정

src/index.css, src/route.js
=> #657 [FIX] exam review edit route

src/pages/AboutPage/AboutPage.jsx
close #646
<br />
- About 스노로즈 리자 지원 버튼에 노션 링크 연결
<br />
=> #646 [CHORE] About 스노로즈에 노션 지원 링크 연결

src/index.css
close #664
<br />
- body에 `overflow: hidden` 설정
=> #664 [STYLE] body의 overflow를 hidden으로 변경

src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
close #670
<br />
- 비밀번호 변경 페이지 내 유효성 조건 수정
<br />
| <img src='https://github.com/user-attachments/assets/3be8073b-9810-4ea8-a040-4090ad6b4b16' width='250' /> |
| 비밀번호 변경 페이지  |
<br />
=> #670 [FIX] 비밀번호 변경 페이지 내 유효성 조건 수정

src/pages/LoginPage/FindIdPage/inputCheck.js, src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx
close #669
<br />
- 백엔드에서 정한 특수문자의 범위와 프런트에서 정한 특수문자의 범위가 서로 달라 생기는 에러를 방지하기 위해서 회원가입 비밀번호 조건을 백엔드에 맞춰 바꾸도록 결정하였습니다.
<br />
=> #669 [FIX] 회원가입 비밀번호 조건 수정

src/apis/login.js, src/apis/signUp.js, src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
close #674
<br />
- 로그인/아이디찾기/비밀번호 찾기 페이지에서 어떤 오류가 나도 그냥 notfound로 가게 했는데,
그것 때문에 자신의 계정이 그냥 틀린 줄 아시는 유저 분들이 계셔서
서버 오류면 서버 오류임을 알려주는 토스트를 추가해서 에러 헨들링을 추가하려고 한다.
<br />
=> #674 [FIX] 서버 오류 토스트 추가하기

src/apis/login.js, src/apis/signUp.js, src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/AuthorizationPage.jsx, src/pages/LoginPage/SignUpPage/SignUpPageStages/UserInfoPage.jsx
close #674 
<br />
- 아이디 찾기/비밀번호 찾기 로직에 500 에러에 대한 토스트 추가
<br />
=> #674 [FIX] 아이디 찾기/비밀번호 찾기에 서버 에러에 대한 토스트 추가

src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindIdPage/FindIdPage.module.css, src/pages/LoginPage/FindPwPage/FindPwPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.module.css
close #683
<br />
- 아이디 찾기 내 설명글 추가
<br />
| <img width="250" src="https://github.com/user-attachments/assets/9c536efa-31e0-461d-ac78-f76689ceeb42" />|
| 아이디 찾기 페이지|
<br />
=> #683 [FEAT] 아이디 찾기 내 설명글 추가

src/components/PostList/PostList.jsx, src/components/PostList/PostList.module.css, src/constants/reactQuery.js, src/hooks/useSearch.jsx, src/pages/BoardPage/BoardListPage/BoardListPage.jsx, src/pages/BoardPage/BoardListPage/BoardListPage.module.css, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css, src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx, src/pages/MyPage/ActivityPage/ActivityPage.module.css, src/pages/NoticeListPage/NoticeListPage.jsx, src/pages/NoticeListPage/NoticeListPage.module.css, src/pages/PostPage/PostSearchPage/PostSearchPage.jsx, src/pages/PostPage/PostSearchPage/PostSearchPage.module.css
close #687
<br />
- 스크롤 영역을 중간 요소로 지정한 경우에 스크롤이 버벅이는 현상이 있었음
- scrollRef을 페이지 상위 요소로 이동함
- 검색 페이지에 누락된 FetchLoading 추가
<br />
=> # 687 [STYLE] 스크롤 영역을 페이지 상위 요소로 변경

src/apis/search.js, src/components/DropDownBlue/DropDownBlue.module.css, src/components/Loading/FetchLoading/FetchLoading.jsx, src/hooks/useSearch.jsx, src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx, src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css, src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
close #647
<br />
- 시험후기 검색 키워드가 없어도 필터링 가능하게 변경
<br />
=> #674 [MODIFY] 시험후기 검색 키워드 없어도 필터링 가능하게 변경

src/pages/LoginPage/FindIdPage/FindIdPage.jsx, src/pages/LoginPage/FindIdPage/FindIdPage.module.css, src/pages/LoginPage/FindPwPage/FindPwPage.jsx, src/pages/LoginPage/FindPwPage/FindPwPage.module.css, src/pages/LoginPage/SignUpPage/SignUpPage.module.css
=> #691 [FIX] 비밀번호 찾기와 아이디 찾기 페이지에서 다음 버튼이 잘 보이게 수정

README.md
close #708
<br />
- 리드미 리뉴얼
<br />
=> #708 [DOCS] README.md 리뉴얼

src/components/Calendar/Calendar.style.jsx, src/index.css
close #715 
<br />
- `.react-calendar`에 대한 css를 index.css로 이동
- index.css에 abbr 스타일 초기화 추가
- color: inherit
- text-decoration: none
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/682a21e8-137b-4f80-b27d-612481138c38"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/19b85eed-ca16-452c-b5b8-bb512e4eeca2"> |
<br />
=> #715 [STYLE] 출석체크 캘린더 스타일 수정

src/components/DropDownBlue/DropDownBlue.module.css
close #717
<br />
- DropDownBlue 컴포넌트의 z-index 삭제
<br />
=> #717 [FIX] 시험후기 필터가 사이드바 위로 올라오는 문제 수정

src/components/PopUp/PopUp.jsx
=> #721 [CHORE] 팝업 공지 내용 수정_20241020

public/ad.txt
close #726
<br />
- ad.txt 파일 추가
<br />
=> #726 [CHORE] ad.txt 파일 추가

src/pages/PostPage/PostPage/PostContent.jsx, src/pages/PostPage/PostPage/PostContent.module.css, src/pages/PostPage/PostPage/PostPage.jsx, src/pages/PostPage/PostPage/PostPage.module.css, src/pages/PostPage/index.js
close #729
<br />
- 하이퍼링크를 인식할 수 있는 PostContent 컴포넌트 개발
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/a1966f16-176c-4072-9b2c-3f54322d2c6b"> |
| 게시글 상세 - 하이퍼링크 인식 |
<br />
=> #729 [FEAT] 게시글 내부에 있는 URL을 하이퍼링크로 인식

src/components/PopUp/PopUp.jsx, src/components/PopUp/PopUp.module.css, src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
close #746 
<br />
- 팝업 공지에서 신규 모집 리자 내용 삭제
- BoardPostList에서 사용하지 않는 console.log 삭제
<br />
=> #746 [CHORE] 팝업 공지에서 신규 모집 리자 내용 삭제

src/pages/BoardPage/BoardListPage/BoardListPage.jsx
close #748
<br />
- 백엔드 API가 준비 안 되어서 베숙트의 검색 기능을 빼달라는 부탁에 뺐습니다. 
<br />
=> #748 [FIX] 베숙트에 검색 기능 없애기

public/index.html
close #764
<br />
- 스노로즈 검색 시 설명글에 react-create-app으로 만들어졌다는 글 대신 커뮤니티에 대한 설명글을 노출시키기 위해 description meta 데이터를 수정했습니다.
<br />
=> #764 [CHORE] description meta 데이터를 스노로즈 설명글로 업데이트

src/apis/account.js, src/apis/index.js, src/hooks/useAuth.js
close #766
<br />
- 로그아웃 API 연결
<br />
=> #766 [FEAT] 로그아웃 API 연결

src/constants/point.js
close #771
<br />
- ENUM 중 FLOODING 대소문자 수정
- `FlOODING` >> `FLOODING`으로 변경
<br />
| <img width="250" src="https://github.com/user-attachments/assets/63537333-f796-4942-b111-45d1416bf9e1" />|
| 이슈 화면 |
<br />
=> #771 [FIX] ENUM 중 FLOODING 대소문자 수정

src/components/PopUp/PopUp.jsx, src/components/PopUp/PopUp.module.css
close #773
<br />
- 2411219 팝업 내용 업데이트
<br />
=> #773 [CHORE] 팝업 공지 내용 업데이트 - 241219

src/components/Route/CheckExamPeriodRoute.jsx
close #775
<br />
- 시험후기 업로드 허용 기간 변경 (241221 ~ 250120)
<br />
=> #775 [CHORE] 시험후기 업로드 허용 기간 변경

src/constants/menus.js, src/pages/BoardPage/BoardListPage/BoardListPage.module.css
close #787
<br />
- 사이드바 메뉴에 베숙트 추가
- 베숙트 페이지 맨 위에 padding 부족으로 postBar 잘리는 css 문제 해결
<br />
<br />
=> #787 [FEAT] 사이드바에서 베숙트 메뉴 추가

src/pages/MainPage/MainPage.jsx
close #807
<br />
- MainPage.jsx서 사용하지 않는 코드 라인 삭제
- 배너 이미지, 공지, 베숙트 조회 api import문
- 로그인 상태 체크 코드
- 팝업 공지 내리기
<br />
=> #807 [CHORE] 팝업 공지 내리기

src/components/PopUp/Component.jsx, src/components/PopUp/Component.module.css, src/components/PopUp/PopUp.jsx, src/components/Route/CheckExamPeriodRoute.jsx, src/pages/MainPage/MainPage.jsx
close #817
<br />
- 팝업 공지글 게시 (250217)
- 새내기 웰컴 이벤트
- 재학생 꿀팁 이벤트
<br />
| <img width="644" alt="image" src="https://github.com/user-attachments/assets/2c87193f-d343-4139-bf76-1c80ad174722" /> |
<br />
=> #817 [CHORE] 팝업 공지글 게시(250217)

src/components/Route/CheckExamPeriodRoute.jsx
close #822
<br />
- CheckExamPeriodRoute의 examEnd를 지난 일자로 수정
<br />
=> #822 [FIX] 시험후기 작성 페이지 접근 못하게 제어

src/shared/component/layout/Header/Header.jsx
close #836 
<br />
- 헤더 로고 클릭 시 홈페이지로 이동 기능 구현
<br />
=> #836 [FEAT] 헤더 로고 클릭 시 홈페이지로 이동 기능 구현

src/apis/userInfo.js, src/feature/my/constant/activity.js
close #841
<br />
- getDonwloadedExamReviews >> getDownloadedExamReviews 오탈자 수정
<br />
=> #841 [FIX] getDownloadedExamReviews으로 오탈자 수정

src/page/home/MainPage/MainPage.jsx
close #862 
<br />
- 팝업 공지 내리기
=> #862 [CHORE] 팝업 공지 내리기

public/index.html
close #873
<br />
- 기존 방식: 모바일에서 focus시 화면이 확대되어, 사용자가 input 입력 후 다시 화면을 줄여야 하는 불편함이 있었음.
- 수정된 방식: `index.html`파일에 meta 태그에 `maximum-scale=1` 속성과 `user-scalable=no` 속성을 적용해주면, focus가 되어도 화면이 확대되지 않아 사용자가 불편함 없이 이용할 수 있음
<br />
| ![IMG_6648](https://github.com/user-attachments/assets/472f2957-e8ea-414b-97a7-28114f77f7d6) | ![IMG_6651](https://github.com/user-attachments/assets/2ff7c61b-28fb-49db-8037-05677f5a860e) |
| 적용 전 - input에 focus시 확대됨 | 적용 후 - input에 focus해도 확대 X | 
| ![IMG_6649](https://github.com/user-attachments/assets/e8eed972-b5e7-4c82-85eb-e985dfa2289c) | ![IMG_6650](https://github.com/user-attachments/assets/a4df9e70-e661-4c68-97b9-36e2d5434b94) |
| 적용 전 - input에 focus시 확대됨 | 적용 후 - input에 focus해도 확대 X | 
<br />
- 해당 옵션을 …
=> #873 [FIX] 모바일에서 focus시 화면 확대되지 않도록 meta에 속성값 설정

src/shared/component/layout/CloseAppBar/CloseAppBar.module.css
close #876
<br />
- rem 변경에 따른 '수정'버튼 크기 미적용으로 css내 font-size 추가
<br />
<br />
=> [FIX] 수정 버튼 글자 크기 

src/ProtectedRoute.jsx, src/feature/exam/lib/CheckExamPeriodRoute.jsx, src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx
close #858
<br />
- admin은 시험후기 작성 페이지에 상시 접근 가능하도록 권한 수정했습니다.
- 시험후기 게시판 ‘시험 유형 및 문항수’ 항목에 placeholder를 수정했습니다.
- 접근 권한이 없는 페이지에 접근 후 노출되는 alert 창에서 확인 버튼을 클릭하면 인증 페이지로 리다이렉트 하도록 수정했습니다.
<br />
=> #858 [FEAT]  스노로즈 1~2월 제언 일부 작업

src/feature/home/component/PopUp/PopUp.jsx
close #869
<br />
- 팝업에서 3월 회계 내용만 삭제 (4/20까지만 게시 예정, 4/21에 merge 해주세요)
<br />
=> #869 [CHORE] 팝업에서 3월 회계 내용만 삭제 (4/20까지만 게시 예정, 4/21에 merge 해주세요)

jsconfig.json
close #893
<br />
- 컴포넌트 클릭 시, 해당 파일로 바로 이동하도록 jsconfig.json 추가
<br />
https://github.com/user-attachments/assets/da54d179-e04f-4196-b5a5-95c93dbe2720
컴포넌트 클릭 시, 해당 파일로 바로 이동
<br />
=> #893 [CHORE] 컴포넌트 클릭 시, 해당 파일로 바로 이동하도록 jsconfig.json 추가

src/feature/home/component/PopUp/PopUp.jsx
close #905
<br />
- 일부 팝업 내용 삭제 
<br />
<br />
- [노션](https://www.notion.so/snorose/e5a1f22d182243a9a930938badd7b6e3?pvs=4#1c37ef0aa3bf80d2818cf3f28b5efc8f)
<br />
=> #905 [CHORE] 일부 팝업 내용 삭제 (4/27까지만 게시 예정, 4/28에 merge 해주세요)

src/feature/exam/lib/CheckExamPeriodRoute.jsx
close #908
<br />
- 시험후기 작성 기간을 **2025/04/29 00:00 ~ 2025/05/05 23:59:59**로 수정했습니다.
<br />
=> #908 [CHORE] 시험후기 작성 기간 변경

src/feature/home/component/PopUp/PopUp.jsx
Reverts snorose/snorose-front-react#928
=> Revert "#919 [REMOVE] 5월 팝업 내 시험 후기 게시판 운영 내용 삭제"

src/feature/home/component/PopUp/PopUp.jsx
|                                                   항목                                                   |        LINK        |
| :------------------------------------------------------------------------------------------------------: | :----------------: |
| <img src="https://upload.wikimedia.org/wikipedia/commons/e/e9/Notion-logo.svg" alt="Notion" width="24"/> |     [Notion](https://www.notion.so/snorose/e5a1f22d182243a9a930938badd7b6e3?pvs=4#1e27ef0aa3bf80ceb669cf07d51d09bf)     |
Close #936
- 팝업에서 시험 후기 내용 삭제
| After |
| :---: |
| <img src='https://github.com/user-attachments/assets/f1a44272-f8c3-4eda-aff4-209f7b02030b' width=250 />      |
> 리뷰어가 집중적으로 확인해야 하는 항목을 선택해 주세요.
=> #936 [SNO-57] 5월 팝업에서 시험 후기 내용 삭제

src/feature/board/component/BoardBar/BoardBar.module.css, src/feature/search/component/Search/Search.module.css, src/page/board/BoardCategoryPage/BoardCategoryPage.module.css, src/shared/component/layout/Header/Header.module.css
Close #963
-> 게시판 카테고리 페이지 폰트 사이즈 수정
- 게시판 카테고리 페이지 폰트 사이즈 수정
| <img width="361" alt="snorose" src="https://github.com/user-attachments/assets/0c5c82a1-170f-418d-95f5-817c228acaed" /> | <img width="360" alt="snorose" src="https://github.com/user-attachments/assets/a1a5bdbc-af87-4682-b2e8-bf247a40ca14" /> |
=> [SNO-69] #963 게시판 카테고리 페이지 폰트 사이즈 수정

src/feature/board/component/NoticeBar/NoticeBar.jsx, src/feature/board/component/NoticeBar/NoticeBar.module.css, src/feature/board/component/PostBar/PostBar.jsx, src/feature/board/component/PostBar/PostBar.module.css, src/feature/search/component/Search/Search.module.css, src/page/board/PostListPage/PostListPage.jsx, src/page/board/PostListPage/PostListPage.module.css, src/shared/component/button/WriteButton/WriteButton.module.css, src/shared/component/layout/BackAppBar/BackAppBar.jsx, src/shared/component/layout/BackAppBar/BackAppBar.module.css
<div align="center" style="border:1px solid #ddd; border-radius:6px; padding:16px; margin:16px 0;">
<p>게시글 리스트 폰트 키우기</p>
</div>
<div align="center" style="border:1px solid #ddd; border-radius:6px; padding:16px; margin:16px 0;">
<p>공지 폰트 키우기</p>
</div>
<div align="center" style="border:1px solid #ddd; border-radius:6px; padding:16px; margin:16px 0;">
<p>검색 폰트 키우기</p>
</div>
Close #958 
- 폰트 키우고, 그에 맞게 UI 수정
- PostListPage
- PostBar
- NoticeBar
- Search
- BackAppBar
- WriteButton
| Before - 게시글 리스트 | After - 게시글 리스트 |
| <img width="366" alt="image" src="https://github.com/user-attachments/assets/313ebc5c-58b2-43af-9fba-e48ee3487068" /> | <img width="364" alt="image" …
=> [SNO-64] #958 게시글 리스트, 공지글 리스트, 검색 리스트 - 폰트 크기 수정

src/assets/icon.svg, src/page/account/LoginPage/LoginPage.jsx, src/page/account/LoginPage/LoginPage.module.css, src/shared/component/input/Input/Input.jsx
|                                                   항목                                                   |        LINK        |
| :------------------------------------------------------------------------------------------------------: | :----------------: |
|  <img src="https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" alt="Figma" width="16"/>  |     [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=4279-18389&m=dev)      |
Close #941
- 로그인 페이지 내 '아이디 기억하기' 기능 구현 ([2025 제언](https://www.notion.so/snorose/1ea7ef0aa3bf81eba770e763bb7d11f5?pvs=4))
- '아이디 기억하기' 활성화 시: 다음 로그인 시 아이디가 자동으로 입력됩니다.
- '아이디 기억하기' 비활성화 시: …
=> #941 [SNO-32] 아이디 기억하기 기능 구현 (2025 제언)

src/feature/my/constant/activity.js
|                                                   항목                                                   |        LINK        |
| :------------------------------------------------------------------------------------------------------: | :----------------: |
|  <img src="https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg" alt="Figma" width="16"/>  |     [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=4964-9842&m=dev)      |
Close #952
- 일러스트 변경
> 리뷰어가 집중적으로 확인해야 하는 항목을 선택해 주세요.
- 일러스트만 변경하였고, 그 외 페이지 내 문구 내용, 폰트 사이즈 등은 다른 브랜치에서 작업 완료하였습니다.
=> #952 [SNO-61] 스크랩한 글 일러스트 변경

src/page/snorose/PolicyPage/PolicyPage.module.css
close #900 
<br />
- 이용약관 내 UI 변경
<br />
| 개인정보 처리방침 | 서비스 이용 약관 |
| <img width=250 src='https://github.com/user-attachments/assets/ce92f1a4-e6d7-41ce-a6f3-db9ae7a39696' /> | <img width=250 src='https://github.com/user-attachments/assets/1d25a4b2-f91d-41ac-a19c-825e51863a52' /> |
=> #900 [STYLE] 이용약관 내 UI 변경

src/feature/home/component/HomeBesookt/HomeBesookt.jsx
Close #968
`HomeBesookt`에서 `PostBar`를 Link로 감쌌습니다.
```jsx
<Link
key={`home-besookt-${besookt.boardId}-${besookt.postId}`}
to={`/board/${getBoardTextId(besookt.boardId)}/post/${besookt.postId}`}
>
<PostBar data={besookt} />
</Link>
```
|        |       |
> 리뷰어가 집중적으로 확인해야 하는 항목을 선택해 주세요.
=> #968 [SNO-76] 홈 베숙트에서 상세 페이지로 이동이 안 되는 문제 수정

src/style/variable.css
Close #961
`variable.css`에서 font-size 단위를 rem으로 변경했습니다.
|        |       |
> 리뷰어가 집중적으로 확인해야 하는 항목을 선택해 주세요.
=> #961 [SNO-71] font size 단위를 rem으로 변경

src/page/account/LoginPage/LoginPage.jsx, src/page/account/LoginPage/LoginPage.module.css
* #941 [FEAT] 로그인 상태 유지 ui 구현
* #941 [FEAT] 로그인 유지 토글 기능 구현
* #941 [CHORE] 축약로 사용하던 함수명을 풀네임으로 변경
* #941 [FEAT] 아이디 기억하기 기능 구현
* #941 [REMOVE] 중복 CSS 속성 삭제
=> [MERGE] 아이디 기억하기 기능 복구 (250517 ver.)

src/feature/home/component/HomeCard/HomeCard.module.css
Close #987
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=4279-18619&m=dev)
- [Notion](https://www.notion.so/snorose/1f47ef0aa3bf80099cb2ef89b2506da1?pvs=4)
- 홈 화면 내 [공지]와 [출석체크] 각각의 너비를 변경했습니다. (제언 내용)
|    <img src='https://github.com/user-attachments/assets/5bafe369-cefd-4611-9b39-c83bee3d6361' width=250 />    |<img src='https://github.com/user-attachments/assets/98290926-0409-4ae9-918f-6713295fb93c' width=250 />       |
=> #987 [SNO-93] 홈화면 내 공지와 출석체크 너비 수정

src/App.jsx, src/index.js
Close #1023
- GrowthBookProvider를 index.js로 옮겼습니다.
|        |       |
=> #1023 [SNO-113] GrowthBookProvider 위치 수정

src/feature/home/component/HomeBoardCard/HomeBoardCard.module.css
Close #1036
- HomeBoardCard 호버 케이스 추가
| <img width="600" alt="image" src="https://github.com/user-attachments/assets/54c868ac-bca8-4ff1-a734-d5adcbc45d2e" /> | <img width="600" alt="image" src="https://github.com/user-attachments/assets/9373e273-1344-4a67-9680-0433b6eb734f" /> |
=> #1036 [SNO-111] HomeBoardCard hover 케이스 적용

src/feature/exam/lib/CheckExamPeriodRoute.jsx
Close #1052
- 시험후기 작성 기간을 **2025년 6월 30일(월) 00:00 ~ 2025년 7월 13일(일) 23:59**으로 업데이트합니다.
=> #1052 [SNO-124] 시험후기 작성 기간 업데이트

src/feature/exam/lib/CheckExamPeriodRoute.jsx
Close #1055
- [운영기획팀 회의록 Notion](https://www.notion.so/snorose/2025-10-2127ef0aa3bf80409377e25da1dbd7b7?source=copy_link#2217ef0aa3bf80ddace9d89244b64410)
- 시험 후기 게시판 기간 연장
- 시험후기 작성 기간 연장 계기: [운영기획팀 회의록 노션](https://www.notion.so/snorose/2025-10-2127ef0aa3bf80409377e25da1dbd7b7?source=copy_link#21d7ef0aa3bf80ab9aa5da311ccde72e)
=> #1055 [SNO-125] 시험후기 작성 기간 연장 (~7.21 23:59)

src/feature/account/component/signUpStep/AccountInfoStep/AccountInfoStep.jsx, src/feature/account/component/signUpStep/AuthorizationStep/AuthorizationStep.jsx, src/feature/account/component/signUpStep/UserInfoStep/UserInfoStep.jsx, src/page/user/ChangePwPage/ChangePwPage.jsx, src/page/user/EditProfilePage/EditProfilePage.jsx, src/shared/component/input/Input/Input.module.css, src/shared/component/input/Input/SpecialInput.module.css
Close #1116 
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=4279-18200&m=dev)
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=4279-18347&m=dev)
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=4279-18287&m=dev)
- 회원가입/아이디 찾기 페이지의 에러 메시지 폰트 크기를 수정
- 문구 어조를 `습니다` >> `해요`로 변경
- `확인해주세요` >> `확인해 주세요`로 띄어쓰기를 어법에 맞게 수정
| <img width="250" height="1266" alt="image" src="https://github.com/user-attachments/assets/2622e5dd-6bf3-4819-bc09- …
=> #1116 [SNO-149] 회원가입/아이디 찾기 페이지 내 error 폰트 사이즈 및 문구 어조 수정

src/page/home/AttendancePage/AttendancePage.jsx, src/shared/component/Toast/Toast.module.css
Close #1163
- 청파제 기념 출석완료 토스트 메시지 문구 변경
| <img width="250" alt="image" src="https://github.com/user-attachments/assets/9e884a6a-8f21-46fd-8106-a87433ef6306" /> | <img width="250" alt="image" src="https://github.com/user-attachments/assets/09bfd063-9f1a-452b-ac1c-e7c06a510969" />|
=> #1163 [SNO-176] 청파제 기념 출석완료 토스트 메시지 문구 변경

src/page/home/AttendancePage/AttendancePage.jsx, src/shared/component/Toast/Toast.module.css
**➡️ [🧚-릴리즈-노트 바로가기](https://discord.com/channels/1218891487312351283/1373224715203645451)**
```
🔧 변경 사항
- 청파제 기념 출석완료 토스트 메시지 문구 변경
```
=> [MERGE] dev to main (250916)

src/App.jsx, src/page/alert/AlertSettingPage/AlertSettingPage.jsx, src/page/alert/AlertSettingPage/AlertSettingPage.module.css
Close #1196 
- [Notion](https://www.notion.so/snorose/iOS-PWA-26d7ef0aa3bf803496aaf187674632e8?source=copy_link)
- 알림 설정 페이지에 안내 설정 안내문을 추가했습니다.
=> #1196 [SNO-204] 알림 설정 안내 UI 추가

src/App.jsx, src/feature/alert/constant/error.js, src/page/alert/AlertSettingPage/AlertSettingPage.jsx, src/shared/component/Modal/NoticeModal/NoticeModal.module.css, src/shared/constant/modalText.js, src/shared/context/ModalContext.jsx, src/shared/lib/dateTime.js
Close #1189 
- [Notion](https://www.notion.so/snorose/2737ef0aa3bf80bfa29bf0e1b8d9b23a?source=copy_link)
- 알림 설정 페이지 > 광고성 알림 수신 컴포넌트의 `onToggle`에 모달 제어 로직 추가
- 불필요한 console.log 삭제
- 알림 에러 메시지 일부 수정
- 디자인 시스템에 맞게 `NoticeModal` CSS 수정
- dateTime.js 유틸에 각 함수가 어떤 포맷으로 변환해주는 지 알 수 있도록 주석 추가
| 광고성 알림 수신 동의 | 광고성 알림 수신 동의 해제 |
| <img width="597" height="831" alt="image" src="https://github.com/user-attachments/assets/5b7564df-feae-417c-bfde-fd626a790922" /> | <img width="595" height="831" alt="image" src="https://github.com/user-attachments/assets/61452522-aa4a-4332-baf5-b0db5204405d" /> |
=> #1189 [SNO-205] 광고성 알림 수신 동의 및 해제 시 팝업이 뜨지 않는 버그 수정

src/feature/home/component/PopUp/PopUp.jsx
Close #1207
- 팝업에 청파제 이벤트 포인트 지급 일정 관련 안내사항 추가
|  <img width="250"  alt="image" src="https://github.com/user-attachments/assets/e106bd38-cb7b-4d23-a939-021766fda652" />  | <img  width="250"   alt="image" src="https://github.com/user-attachments/assets/b36c40a3-a79f-4b97-b8b7-065a5e4b9b70" /> |
=> #1207 [SNO-211] 팝업에 청파제 이벤트 포인트 지급 일정 관련 안내사항 추가

public/firebase-messaging-sw.js
Close #1211
- [Notion](https://www.notion.so/snorose/or-or-2747ef0aa3bf80669c57ef825fb5895b?source=copy_link)
- 알림 데이터를 notification이 아닌 data로 받아옴
- 수동으로 알림을 띄우도록 코드 수정
- 'notificationclick' 이벤트에 대해 `/alert` 라우트로 이동하도록 핸들러 등록
배포 이후엔 알림함이 아닌 알림과 직접적으로 연관된 페이지로 바로 이동할 수 있도록 수정할 예정입니다.
=> #1211 [SNO-215] 푸시 알림 클릭 시 알림함으로 네비게이트

src/apis/post.js
Close #1234
- patchPost body 수정
=> #1234 [SNO-217] 게시글 수정 안 되는 이슈 패치
