src/components/BoardCard/BoardCard.jsx

close #56 
<br />
- BoardCard 컴포넌트의 Cannot find module 에러 해결
<br />
- `BOARD_MENUS` 상수의 image 속성값이 변경되어 발생한 에러입니다.
- 기존
```js
export const BOARD_MENUS = [
{
id: 'firstSnow',
to: '/board/first-snow',
title: '첫눈온방',
desc: '눈송이 모두가 이용하는 커뮤니티',
image: 'firstSnow.svg',
}
];
```
- 변경
```js
import firstSnow from '../assets/images/firstSnow.svg';
export const BOARD_MENUS = [
{
id: 'firstSnow',
to: '/board/first-snow',
title: '첫눈온방',
desc: '새내기 전용 커뮤니티',
image: firstSnow,
}
];
```
- 기존은 파일명만 받아와 BoardCard에서 경로를 완성하여 렌더링했지만, `BOARD_MENUS`의 image 속성이 온전한 이미지로 변경되면서 BoardCard의 기존 코드에 문제가 발생하게 되었습니다.
- 변경된 상수 내용에 맞춰 BoardCard에서 `backgroundImage` prop으로 받아온 것을 inline css에 바로 사용하여 해결했습니다.
<br />
- `BOARD_MENUS` 상수의 image 속성값이 변경되어 `BOARD_MENUS`를 사용하고 있던 BoardCard 컴포넌트에 문제가 생긴 케이스였습니다.
- 다른 컴포넌트에 영향을 줄 수 …

#56 [FIX] BoardCard 컴포넌트의 svg Cannot find module 에러 해결

---

src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
src/pages/MyPage/ViewPointListPage/ViewPointListPage.module.css

close #87
<br />
- 포인트 내역 보기 페이지 view 구현
- 상단에 BackAppBar 컴포넌트 사용
- 포인트 내역은 더미데이터 사용 (API는 추후 연동 예정)
<br />
|<img width="289" alt="image" src="https://github.com/user-attachments/assets/a72248ad-8c83-4ef6-990d-432070871bb0"> |
|포인트 내역 보기 |
<br />

#87 [FEAT] 포인트 내역 보기 페이지 UI 구현

---

src/components/Navbar/Navbar.jsx

close #80
<br />
- localhost:3000에 있을 때 Navbar의 홈 아이콘이 활성화 되지 않는 문제가 있었습니다.
- pathname을 split한 결과가 빈 문자열이면 `currentMenu`에 'home'을 할당해 문제를 해결했습니다.
```js
const currentMenu = pathname.split('/')[1] || 'home';
```
<br />
| <img width="679" alt="image" src="https://github.com/user-attachments/assets/6c5b20b1-0174-4b97-b883-0ae3e9696801"> |

#80 [FIX] localhost:3000에 있을 때 Navbar의 홈 아이콘이 활성화되지 않는 문제 해결

---

src/ProtectedRoute.jsx
src/apis/examReview.js
src/contexts/ToastContext.jsx
src/index.js
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx

close #105
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/6041af2c-afd6-4209-a317-174118f621d5"> |
| API 에러가 발생한 경우 |
<br />
- 시험후기 리스트 API가 에러를 응답으로 보낼 때 화면이 죽어버리는 문제가 발생했습니다.
- 에러를 응답으로 받아도 화면이 죽지 않도록, `useInfiniteQuery`에서 `status`를 꺼내 값이 'error'이면 응답 결과를 렌더링하지 못하게 막았습니다.
- ProtectedRoute.jsx 로그인 권한 확인 로직에 alert 추가했습니다.
- 미로그인 사용자가 로그인이 필요한 기능에 접근 시 alert으로 경고창이 발생한 후 메인 페이지로 돌아갑니다.

#105 [FIX] 시험후기 리스트 API 에러 핸들링

---

src/components/Header/Header.jsx
src/components/Header/Header.module.css
src/index.css

close #101
<br />
- 로그인 상태에 따라 Header에 로그인/로그아웃 버튼 핸들링
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/b567be33-e283-4dd7-bd4a-cb9baa58ddcd"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/1b09bed6-4da8-45f6-975c-47e83d3dc7cd"> |
| 로그인 상태인 경우 | 미로그인 상태인 경우 |

#101 [FEAT] 로그인 상태에 따라 Header에 로그인/로그아웃 버튼 핸들링

---

src/apis/userInfo.js
src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx
src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.module.css

close #69
<br />
- close 버튼 구현
- 탈퇴 관련 문구 내용 일부 수정
- `뒤로가기` 버튼 클릭시 이전 페이지의 해당 탭으로 이동하는 기능 구현
- `탈퇴하기` 버튼 클릭시 alert창 띄우는 기능 구현
- 회원탈퇴 API 연동
<br />
| <image src="https://github.com/user-attachments/assets/652118f0-f7eb-4280-a383-738ef0aca4dd" width="250"> |
|회원 탈퇴 페이지 |
<br />

#69 [MODIFY] 회원탈퇴 페이지 UI 수정 및 API 연동

---

src/apis/index.js
src/apis/userInfo.js
src/hooks/useAuth.js
src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.jsx

close #126
<br />
- 회원탈퇴 API 코드 개선
- 비밀번호 확인 입력창 임시 추가
- 회원 정보 관련 API 파일 생성
<br />
| <image width='250' src='https://github.com/user-attachments/assets/c726a147-59ca-4c17-98e1-2af1f03aadb6' >|
|회원 탈퇴 페이지|
<br />
- 비밀번호를 입력해야 회원탈퇴 가능합니다. 그런데 현 UI에는 비밀번호 입력창이 없으므로, 디자이너에게 해당 부분 수정 작업을 요청해두었습니다. 디자인 수정 완료 후에 기능 완성하도록 하겠습니다.
<br />

#126 [FEAT] 회원탈퇴 API 코드 개선 및 비밀번호 확인 입력창 추가

---

src/pages/MyPage/ActivityPage/ActivityPage.module.css
src/pages/MyPage/DeleteAccountPage/DeleteAccountPage.module.css
src/pages/MyPage/PolicyPage/PolicyPage.module.css
src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
src/pages/MyPage/ViewPointListPage/ViewPointListPage.module.css
src/route.js

close #131
<br />
- bottom navigation이 필요없는 페이지는 제거
- padding-bottom 크기를 54px로 통일하여 조정
<br />
- 1 depth 페이지 (메인홈, 게시판, 시험후기, 알림, 마이페이지)에는 `bottom navigation` 배치
- 2 depth 페이지에는 `bottom navigation` 노출 X
<br />

#131 [MODIFY] bottom navigation이 필요없는 페이지는 제거 및 padding-bottom 크기 조정

---

src/components/WriteButton/WriteButton.jsx
src/components/WriteButton/WriteButton.module.css
src/components/WriteButton/index.js
src/pages/BoardPage/BoardListPage/BoardListPage.jsx
src/pages/BoardPage/BoardListPage/BoardListPage.module.css
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx

close #150
<br />
- 시험후기 작성 페이지에서 온라인 수업 여부를 입력받는 선택 필드 추가
- 시험후기 게시판과 일반 게시판에 글작성 플로팅 버튼 추가
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/46c6db94-000c-4164-a735-27bd0c5f980b"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/72456889-28d1-42d8-bf0c-7de669d8783a"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/78c433fa-0e31-4282-afdd-bb3403368738"> |
| :---------------------: | :---------------------: | :---------------------: |
| 시험후기 작성 페이지 - `온라인 필드` | 시험후기 게시판 - 플로팅 버튼 | 일반 게시판 - 플로팅 버튼 |
<br />
- `WriteButton` 컴포넌트는 글작성 플로팅 버튼입니다.

#150 [STYLE] 시험후기 작성 페이지 온라인 선택 필드 추가 & 글작성 플로팅 버튼 추가

---

src/apis/notice.js
src/pages/BoardPage/BoardListPage/BoardListPage.jsx
src/pages/NoticeListPage/NoticeListPage.jsx

close #156
<br />
- 각 게시판에서의 공지글 리스트 조회 API 연결
- 공지글 클릭 시, 공지글(=게시글) 상세 페이지로 이동
- 각 게시판에서의 공지글 1줄 조회 API 연결
<br />
<br />

#156 [FEAT] 공지글 조회 API 연결

---

src/constants/modalOptions.js
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css

close #173
<br />
- 시험후기 삭제/수정 모달 연결했습니다.
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/58440c91-4638-4052-9131-24f744d54c7b"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/9104ed73-2b0a-4801-8d70-e4963804ac7a"> |
| 옵션 모달 | 삭제 모달 |
<br />
- 변경된 시험후기 상세 페이지의 라우트가 시험후기 수정 로직에 반영이 안 되어서 수정 완료 후 상세 페이지로 못 돌아가는 문제가 있습니다. 해당 문제는 따로 작업한 후 올리겠습니다.

#173 [FEAT] 시험후기 상세 페이지에 수정/삭제 모달 연결

---

src/components/Toast/Toast.module.css
src/index.css

close #174
<br />
- 기존 Toast가 눈에 잘 띄지 않아 위치를 정중앙으로 이동시켰습니다.
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/95157bdc-ffb2-40aa-b8d7-e3e415a0b14c"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/1b0c924d-ed40-46cb-b890-6b2fdb0131e4"> |
| 기존 | 변경 후 |
<br />
그리고 배경색이 너무 투명해서 메시지가 잘 보이지 않아 투명도를 변경하려고 합니다.
어느 것이 더 나은 지 의견주시면 반영하겠습니다 :)
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/1b0c924d-ed40-46cb-b890-6b2fdb0131e4"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/8a5d3707-1603-40ac-a547-8bc4d1cb1707"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/259549b2-929e-4589-9b98-4f72 …

#174 [STYLE] Toast 위치를 정중앙으로 수정

---

package.json
src/apis/point.js
src/constants/point.js
src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx
yarn.lock

close #162
<br />
- 잔여 포인트 API 연동 (페이지 상단)
- 포인트 내역 보기 페이지 API 연동
- `date-fns` 라이브러리 추가
- `POINT_CATEGORY_KOREAN_ENUM` 코드 추가
<br />
| <img width='250' src='https://github.com/user-attachments/assets/c758d9c4-bdde-4ed9-b757-52aa2ce10cb0'> |  <img width='250' src='https://github.com/user-attachments/assets/89c5346d-0bea-4848-9549-f5e1a4034adb'> |
| 포인트 내역 보기 - 내역이 있을 경우 | 포인트 내역 보기 - 내역이 없을 경우 |
<br />

#162 [FEAT] 포인트 내역 보기 페이지 API 연동

---

src/apis/index.js
src/components/Comment/Comment/Comment.jsx
src/components/Comment/NestedComment/NestedComment.jsx
src/components/Loading/FetchLoading.module.css
src/components/PostBar/PostBar.jsx
src/components/index.js
src/constants/boardMenus.js
src/constants/toast.js
src/hooks/index.js
src/hooks/useComment.jsx
src/hooks/useLike.jsx
src/hooks/useScrap.jsx
src/pages/PostPage/PostPage/PostPage.jsx
src/pages/PostPage/PostWritePage/PostWritePage.jsx
src/pages/PostPage/PostWritePage/PostWritePage.module.css

close #181
<br />
- 좋아요 로직을 스크랩과 일치시키도록 수정
- 수정된 로직을 게시글, 댓글, 대댓글에 적용함 (시험후기 쪽은 별도 적용 필요)
- useScrap에도 자기글 스크랩 못하도록 토스트 설정
- PostPage 'views' 글자 크게 뜨던 거 span태그로 처리해서 다시 작게 수정
- useComment에 alert를 Toast로 수정
- PostBar에 좋아요와 스크랩 여부에 따라 아이콘 색 채움 
- 게시판 리스트에서 '베숙트' 제외 (주석 처리)
- 게시글 작성 페이지의 바닥 흰 배경 오류 수정
- 게시글 작성 페이지 유저 이름 데이터 받아와 띄우기
<br />
| <img width="609" alt="image" src="https://github.com/user-attachments/assets/5693b10a-3a55-4f13-834d-ce00a538fdf1"> | <img width="608" alt="스크린샷 2024-08-26 오후 3 09 55" src="https://github.com/user-attachments/assets/9f4164ef-e16d-4395-9ec1-b768a2f0f2c7">  |  
| :---------------------: | :---------------------: | 
| 베숙트 제외  | 좋아요 스크랩 여부에 따라 아이콘 색 |
| <img width="611" alt="image" src="https://github.com/user-attachments/assets/4abcae40-da44-425f-8e11-d6caa53 …

#181 [REFACTOR] 좋아요 로직 수정

---

src/components/Loading/FetchLoading.jsx
src/components/Loading/FetchLoading.module.css
src/components/NoticeBar/NoticeBar.jsx
src/components/NoticeBar/NoticeBar.module.css
src/pages/BoardPage/BoardListPage/BoardListPage.jsx
src/pages/NoticeListPage/NoticeListPage.jsx

close #183
<br />
- NoticeBar에 PostBar와 같은 폰트 사이즈 적용 & vertical-bar 제거
- FetchLoading 컴포넌트 수정 - (animation=true) 옵션 선택 가능
- 게시글 리스트 페이지와 공지글 페이지에 FetchLoading 추가
<br />
| <img width="610" alt="스크린샷 2024-08-26 오후 6 31 18" src="https://github.com/user-attachments/assets/e29a196c-4b6a-47b5-b2e3-7cc8835d3a64"> | <img width="617" alt="스크린샷 2024-08-26 오후 6 33 18" src="https://github.com/user-attachments/assets/ba1e3c98-a2ab-4c10-aa52-0821bcb79ac8">  |  
| :---------------------: | :---------------------: | 
| isLoading=true  | isError=true |
* 서버 에러로 공지글 리스트 관련 스크린샷은 미첨부

#183 [STYLE] NoticeBar UI 수정 & FetchLoading 적용

---

src/components/Comment/Comment/Comment.module.css
src/constants/toast.js
src/hooks/useScrap.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css

close #186 
<br />
- 스크랩 api 응답 멤버 변수 중 isScrap => isScrapped으로 변경된 것 반영
- 내 게시글 스크랩 시 토스트로 경고 띄우기
- 스크랩 기능을 기존 상단 북마크 아이콘에서 하단 액션 아이콘으로 이동(상단 북마크 아이콘은 삭제)
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/ac05733b-4739-44fb-ba37-8463cef268fe"> |
| 내 게시글 스크랩한 경우 |
<br />
- 내 게시글 스크랩  시 발생하는 에러 핸들링 로직은 `useScrap`에 추가했습니다.
- toast 띄우는 로직

#186 [FEAT] 스크랩 에러 핸들링 및 시험후기 페이지 스크랩 아이콘 수정

---

src/components/MenuIcon/MenuIcon.jsx
src/components/Sidebar/Sidebar/Sidebar.jsx
src/constants/menus.js

close #190
<br />
- 수정된 라우트 경로 적용 및 2차 배포로 변경된 기능 숨김 처리
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/dcdc49f5-d136-4885-822b-2d484279be25"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/91dd91a8-d25d-4b8c-82ee-71f21298e4cf"> |
| 수정 전 사이드바 | 수정 후 사이드바 |
- useScrap에서 중복 import 오류가 발생할텐데, 해당 오류는 따로 수정해서 PR 올려뒀습니다.
- 임시로 중복 import 삭제 후 확인해주시면 됩니다.

#190 [MODIFY] 사이드바에서 변경된 경로 수정 및 2차 배포로 밀린 기능 숨김

---

src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx

close #200
<br />
- 시험후기 상세 페이지 하단 댓글 아이콘 색상을 #D9D9D9으로 변경
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/c97f6ea7-2514-4163-87c3-c81331b83e01"> |
| 시험후기 하단 댓글 아이콘 색상 변경 |
<br />

#200 [STYLE] 시험후기 상세 페이지의 댓글 아이콘 색상 회색으로 변경

---

src/constants/point.js

close #210
<br />
- `포인트 내역 보기` 페이지 내 `시험후기 삭제` enum 추가
<br />
| <img width='250' src='https://github.com/user-attachments/assets/959165fe-75b2-4640-8d5b-3fb11a7bf87c'> |  <img width='250' src='https://github.com/user-attachments/assets/b06c3b00-33fd-429e-9d63-2b50e7db0a95'> |  
| :---------------------: |  :---------------------: | 
<br />

#210 [MODIFY] 포인트 내역 보기 내 '시험후기 삭제' enum 추가

---

src/components/InputBar/InputBar.jsx
src/constants/toast.js
src/hooks/useComment.jsx

close #216
<br />
- 댓글 생성 / 삭제 포인트 API 연결
<br />
| <img width="615" alt="스크린샷 2024-08-30 오전 1 15 25" src="https://github.com/user-attachments/assets/5f66f90d-9174-4f52-8bc5-c2ef99c60e06"> | <img width="617" alt="스크린샷 2024-08-30 오전 1 16 45" src="https://github.com/user-attachments/assets/d9e203b3-e6ca-45de-ad3d-4ad8cff54a46"> |
| 댓글 생성 | 댓글 삭제 |
<br />
- 글 작성으로 포인트 받는 데에는 한계가 있는데 그 부분 백엔드 미구현인 것 같음
- 현재는 제한없이 글 쓰는대로 다 포인트 받음
<br />

#216 [FEAT] 댓글 포인트 API 

---

src/constants/role.js
src/pages/MyPage/EditInfoPage/EditInfoPage.jsx
src/pages/MyPage/EditInfoPage/EditInfoPage.module.css

close #212
<br />
- `준회원` 이외의 등급에서는 이름, 생년월일 변경 불가를 보여주도록 UI 수정
<br />
| <img width='250' src='https://github.com/user-attachments/assets/104d5c66-12da-4316-b05a-32e54dad84b6'> |  <img width='250' src='https://github.com/user-attachments/assets/db317cc8-8056-4be9-8766-eb654351f69d'> |  
| :---------------------: |  :---------------------: | 
| 준회원 - 수정 가능 | 그 외 - 수정 불가 |
<br />
- 이전에 준희가 approve 했는데, 코드 충돌 과정에서 문제가 생겨 다시 PR 올립니다. 
(#217 코드 내용 동일)
<br />

#212 [MODIFY] 이름, 생년월일 변경 불가를 보여주도록 UI 수정

---

src/components/InputBar/InputBar.jsx
src/components/InputBar/InputBar.module.css

close #253
<br />
- InputBar에 textAreaAutosize 설정
- 5줄까지 보여주고 그 후론 스크롤 생김 (에타 참고)
<br />
| <img width="350" alt="스크린샷 2024-09-01 오후 2 55 02" src="https://github.com/user-attachments/assets/732217ce-9405-4c6a-a798-eec1ff40970a"> |
| 5줄 제한 textareaAutosize 설정 |
<br />

#253 [STYLE] InputBar에 textAreaAutosize 설정 (5줄까지 보여주고 그 후론 스크롤 생김)

---

src/components/AppBar/CloseAppBar/CloseAppBar.jsx
src/components/Toast/Toast.jsx
src/constants/toast.js
src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx

close #268
<br />
- 체크박스 필드의 라벨을 명확하게 수정
- questionDetail을 필수 입력으로 변경
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/a56ff0ca-e49c-445b-bfd1-72397ad89ce4"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/f5e8359a-72ad-43d3-8403-9e946db46798"> |
| 수정 전 화면 | 수정 후 화면 |
<br />
- Toast가 3초 뒤에도 언마운트 되지 않는 문제가 발생했습니다.
- 언마운트하는 로직에서 파라미터를 잘못 전달하는 문제가 있어 수정했습니다.
- 시험후기 작성 페이지의 CloseAppBar에서 X 아이콘이 안 보이는 문제가 있었습니다.
- CloseAppBar의 stroke prop을 default parameter로 두어서 아무 값도 지정하지 않으면 검은색으로 설정되게 수정했습니다.

#268 [MODIFY] 시험후기 페이지 questionDetail 필수 입력으로 변경

---

src/pages/MyPage/ActivityPage/ActivityPage.module.css
src/pages/MyPage/ActivityPage/CommentPage.jsx
src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
src/pages/MyPage/ActivityPage/MyPostPage.jsx
src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
src/pages/MyPage/ActivityPage/ScrapPage.jsx

close #208
<br />
- 글이 없을 경우 나타나는 일러스트 이미지 변경
- [마이페이지] - [내 활동] 탭 내 모든 페이지 변경 
<br />
|<img width='250' src='https://github.com/user-attachments/assets/1df536ad-2bc0-41fe-b248-fac2458d4902'> |<img width='250' src='https://github.com/user-attachments/assets/84b508e2-ff33-4a1e-9732-1e6d68d9098a'> |
| :---------------------: |:---------------------: |
|작성한 글이 없는 경우 |작성한 댓글이 없는 경우 | 
|<img width='250' src='https://github.com/user-attachments/assets/a8f20676-6007-496f-b420-1e7247f56013'> |<img width='250' src='https://github.com/user-attachments/assets/3d57369d-545f-442e-ae0d-edc35e869755'> |
| :---------------------: |:---------------------: |
|작성한 글이 없는 경우 |작성한 댓글이 없는 경우 | 
<br />

#208 [MODIFY] 글이 없을 경우 나타나는 일러스트 이미지 변경

---

src/components/Calendar/Calendar.jsx
src/constants/attendance.js
src/constants/index.js
src/pages/AttendancePage/AttendancePage.jsx

close #275
<br />
- 알림 토글 주석 처리
- 해당 월 출석 여부에 따라 하단 메시지 다르게 보여주기
- 달력의 prev, next을 클릭했을 때 month와 view가 일치하지 않는 문제 수정
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/799f30fb-f446-4d85-8d84-f6b568371716"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/007c45b2-8d5c-452e-af29-04f342e2b352"> |
| 첫 출석인 경우 | 이미 출석 이력이 있는 경우 |
<br />
- 달력의 next, prev navigation 버튼을 클릭했을 때 가끔씩 month와 view가 일치하지 않는 문제가 있었습니다.
- `activeStartDate`를 핸들링하는 로직을 추가해서 month가 변경되었을 때 일치하는 view가 보여지도록 했습니다.
<br />

#275 [MODIFY] 해당 월의 첫 출석인지 아닌지에 따라 다른 메시지 노출

---

src/components/Calendar/Calendar.jsx
src/components/Calendar/Tile/Tile.jsx
src/components/Loading/FetchLoading.module.css
src/pages/AttendancePage/AttendancePage.jsx
src/pages/AttendancePage/AttendancePage.module.css
src/pages/BoardPage/BoardListPage/BoardListPage.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
src/pages/PostPage/PostPage/PostPage.jsx
src/route.js
src/utils/findRoute.js

close #299
<br />
- 출석체크 페이지에서 출석체크 버튼 클릭 후 응답 완료될 때까지 버튼 비활성화
- 시험후기 상세에서 로딩 상태일 때 FetchLoading 컴포넌트가 보이게 수정했습니다.
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/91e148b8-e332-42f7-8c8a-7cff6c1c5fa6"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/1a751c18-124e-4bab-93c5-b81a6cd8ecd8"> |
| 출석체크 버튼 클릭 시 버튼 비활성화 | 시험후기 상세 페이지 로딩 중 |
<br />
- 시험후기 검색 페이지에서 Navbar 보이지 않는 문제 수정
- 시험후기 페이지에서 검색 상태일 경우 라우트에 /search/:keyword가 추가됨에 따라 Navbar 렌더링을 결정하는 함수인 `findRouteByPath`에서 시험후기 검색에 대한 라우트를 제대로 찾지 못하는 문제 때문에 발생한 문제였습니다.
- `findRouteByPath`함수에서 영어뿐만 아니라 다른 문자도 매치할 수 있도록 정규표현식을 수정했습니다.
<br />
- 현재 서버쪽 pagination 응답이 바뀜에 따라 pagination 이 적용된 페이지는 오류가 발생합니다.
- 해당 이슈를 해결한 코드는 …

#299 [FEAT] Fetch 중일 때 FetchLoading 컴포넌트 보여주기

---

src/ProtectedRoute.jsx

close #321
<br />
- ProtectedRoute에서 유저 정보의 `status`가 loading 상태인 경우 fetch가 끝날 때까지 기다리기 위해 `undefined`를 반환하도록 수정했습니다.
<br />
- 권한이 필요한 페이지에서 새로고침 시 권한 없음으로 메인 페이지로 돌아가는 문제
- ProtectedRoute에서 유저 정보를 fetch할 때까지 기다리기 위해 `status`가 loading일 때 `undefined`를 반환
<br />

#321 [FIX] ProtectedRoute에서 유저 정보 status가 loading일 경우 undefined를 반환하도록 수정

---

src/hooks/useAuth.js

close #323
<br />
- 로그아웃 시 캐시된 유저 정보를 삭제
<br />
- 로그아웃 후 곧바로 로그인 했을 때 로그인 권한을 얻지 못 하는 문제가 있었습니다.
- 다시 로그인 했을 때 유저 정보를 새로 가져오는 게 아니라 로그아웃 후 캐시된 유저 정보를 가져와서 발생한 문제였습니다.
- 로그아웃 시 캐시된 유저 정보를 삭제하는 코드를 추가하여 해결했습니다.
<br />

#323 [FIX] 로그아웃 시 유저 정보 캐시를 삭제

---

src/pages/PostPage/PostPage/PostPage.jsx
src/pages/PostPage/PostPage/PostPage.module.css

close #326
<br />
- 배포버전에서 span에 대한 스타일이 안 먹어, 따로 클래스 빼서 지정해주었음
<br />

#326 [FIX] views 클래스로 따로 스타일 지정

---

src/ProtectedRoute.jsx
src/route.js

close #329 
<br />
- 로그인 필요한 메뉴 클릭 시 로그인 페이지로 이동
- 게시판 검색 권한에 따른 접근 제한 안 됐던 거 수정 (boardlist에 'all' 추가)
- 권한에 따른 공지 페이지 접근 제한 (router.js에서 공지 부분에 ProtectedRoute 추가)
<br />
| <img width="1512" alt="스크린샷 2024-09-12 오후 10 43 33" src="https://github.com/user-attachments/assets/0557d2fd-9dbc-469c-a0f0-dd4599e1b1f8"> | <img width="1512" alt="스크린샷 2024-09-12 오후 10 43 05" src="https://github.com/user-attachments/assets/ac4e814a-71c1-4bbc-873d-e315c098d3c5"> |
| 로그인 안 했을 때 공지 클릭 시 | 준회원이 공지 클릭 시 |

#329 [FIX] 메인 화면에서 공지글 & 게시글 검색 - 접근 권한 설정

---

src/constants/boardMenus.js
src/pages/MainPage/MainPage.jsx
src/route.js

close #332
<br />
- (코드, 테스트 등 변경 사항과 변경 이유를 작성해주세요.)
<br />
| <img width="369" alt="스크린샷 2024-09-13 오전 12 31 25" src="https://github.com/user-attachments/assets/9f765c8c-40db-4427-b3bd-e54c45cac779"> | <img width="369" alt="스크린샷 2024-09-13 오전 12 31 36" src="https://github.com/user-attachments/assets/3c9eb0f9-0328-4c4d-96c9-7ada429e2049"> |
| 전체공지 게시판 | 공지 상세 보기 |
<br />
- 전체공지 작성 페이지는 다음 PR에서 작업할 예정
<br />

#332 [FEAT] 메인페이지 전체공지 게시판 연결

---

src/components/PostBar/PostBar.jsx
src/components/PostBar/PostBar.module.css
src/constants/modalOptions.js
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css

close #337
<br />
- 인증된 시험후기의 경우 옵션 모달에서 수정하기 메뉴 숨김
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/8710a30e-1016-4de3-92e0-6f21131965ae"> | <img width="321" alt="image" src="https://github.com/user-attachments/assets/364d5857-7234-4d03-b684-4c9ea454c1db"> |
| 인증된 시험후기 옵션 모달 | 인증된 시험후기 리스트 아이템에 인증 마크 부여 |
<br />

#337 [FIX] 인증된 시험후기는 옵션 모달에서 수정 메뉴 숨김

---

src/hooks/useSearch.jsx
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx

close #342
<br />
- 시험후기 상세에서 리스트로 돌아올 때 필터 유지되도록 수정
<br />

#342 [FIX] 시험후기 필터 유지되도록 수정

---

src/constants/menus.js

close #352
<br />
- 사이드바에 누락된 공지사항 메뉴 추가
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/47ec8947-d23d-4351-a27c-b402b8099491"> |
| 공지사항 메뉴 추가 |
<br />

#352 [FIX] 사이드바에 누락된 공지사항 메뉴 추가

---

src/components/Comment/CommentList/CommentList.jsx
src/components/Loading/FetchLoading.module.css
src/hooks/useComment.jsx
src/hooks/usePagination.jsx

close #367
<br />
- useComment에서 pagination 로직을 분리했습니다.
<br />
- 댓글 페이지네이션에서 0부터 n 페이지까지를 한 번에 호출하는 문제
- useComment에 pagination 로직이 포함되어 있는데, CommentList와 Comment 컴포넌트가 useComment에 대한 의존성을 가지면서 pagination 로직이 중복으로 실행이 된 것 같습니다.
- useComment에서 pagination 로직을 분리해서 해결했습니다.
<br />

#367 [FIX] 댓글 페이지네이션 버그 수정

---

src/components/ReviewContentItem/ReviewContentItem.jsx
src/components/ReviewContentItem/ReviewContentItem.module.css
src/constants/align.js
src/constants/index.js
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx

close #
<br />
- `tag`에 flex-shrink: 0으로 설정, margin-right 추가
- 시험 유형 및 문항 수 영역에 align을 flex-start로 지정
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/617cc8ea-19ce-406d-a896-4726d71aa1c7"> |
| 시험후기 상세 |
<br />

#371 [STYLE] 시험 유형 및 문항 수 라벨이 안 찌그러지게 정렬 수정

---

src/components/ReviewDownload/ReviewDownload.jsx
src/utils/index.js
src/utils/window.js

close #376
<br />
- 모바일 환경에서는 브라우저에서 자체적으로 파일 다운로드 의사를 묻는 confirm과 완료 overlay를 띄우고 있습니다.
- 프론트에서 띄우는 토스트는 모바일 환경에서 제공하는 overlay 제어 흐름에서 벗어나기 때문에 사용자에게 혼란을 줄 여지가 있습니다.
```
ex) 모바일에서는 다운로드 확인 의사를 묻는 confirm 창에서 확인을 눌러야만 실제 파일이 다운로드 됩니다. 
만약 취소를 누를 경우 파일은 다운로드 되지 않고, 프론트 코드에 의해 다운로드 확인 토스트가 노출됩니다.
```
<br />

#376 [MODIFY] PC 환경에서만 시험후기 다운로드 완료 토스트 노출

---

src/components/ReviewDownload/ReviewDownload.jsx

모바일 환경에서 동일한 이름의 파일을 다운로드 시 발생하는 문제를 차단하기 위해 타임스탬프 추가합니다.
close #379
<br />
- 시험후기 다운로드 파일명 뒤에 타임스탬프 추가
<br />
- 모바일 환경에서 시험후기 다운로드 시 동일한 파일명이 존재하는 경우 브라우저 내부에서 자체적으로 발생하는 confirm 창으로 인해 프론트 제어 흐름을 잃게 됨
- confirm창에서 취소를 누르는 경우 파일 다운로드가 안 되지만, 서버에 다운로드 이력이 남게 되는 문제 발생.
- 동일한 파일명 존재 시 발생하는 confirm 창을 사전에 차단하기 위해 다운로드 파일명 뒤에 타임스탬프를 추가함
<br />

#379 [FIX] 다운로드 파일명 뒤에 타임스탬프 추가

---

src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css
src/pages/NoticeListPage/NoticeListPage.jsx
src/route.js

close #397
<br />
- 시험후기 공지 게시판 추가
<br />
| <img width="615" alt="스크린샷 2024-09-15 오후 6 04 01" src="https://github.com/user-attachments/assets/f9b63723-bf2a-41f1-a8f3-ae8e43dc36d6"> | <img width="617" alt="image" src="https://github.com/user-attachments/assets/8231236b-33a9-4eb6-8c21-5d9d28aace3c"> |
<br />

#387 [FEAT] 시험후기 공지 게시판 추가

---

src/pages/MyPage/ChangePasswordPage/ChangePasswordPage.jsx
src/pages/MyPage/EditInfoPage/EditInfoPage.jsx

close #392
<br />
- 변경전) `새 비밀번호`와 `새 비밀번호 확인`이 동일하게 입력되면, 조건에 맞지 않는 비밀번호 형식을 입력해도 submit 버튼이 활성화 됨
- 변경후) `새 비밀번호`와 `새 비밀번호 확인`을 동일하게 입력하여도, 유효성 검사를 통과하지 못하면 submit 버튼 비활성화되도록 수정
<br />
| <img height='500' src='https://github.com/user-attachments/assets/5bd3c79e-08f3-4281-a927-ca79097d5daa'> |  <img height='500'  src='https://github.com/user-attachments/assets/40961b74-42a2-40fb-8878-8746798470a1'> |  
| :-----:|:------:|
<br />
- `새 비밀번호`와 `새 비밀번호 확인` 모두 유효성 검사를 통과하지 않으면 submit 버튼이 비활성화 되므로, 빈 토스트가 노출되는 문제도 함께 해결됨
<br />

#392 [FIX] 새 비밀번호와 확인을 동일하게 입력하여도, 유효성 검사를 통과하지 못하면 submit 버튼 비활성화되도록 수정

---

src/pages/MyPage/MyPage/AccountTab.jsx

close #396
<br />
- 마이페이지 내 계정정보 항목에 이름 추가 및 생년월일 형식 변경
<br />
| <img height='500' src='https://github.com/user-attachments/assets/8c7571b2-9951-4ffd-986b-2c5a19e4645c'> | 
|:---------------:|
| [마이페이지] - [계정 정보] 탭 | 
<br />

#396 [FEAT] 마이페이지 내 계정정보 항목에 이름 추가 및 생년월일 형식 변경

---

src/components/Comment/Comment/Comment.jsx
src/components/InputBar/InputBar.jsx
src/contexts/CommentContext.jsx

close #400
<br />
- 댓글 수정 시 빈 토스트만 뜨고 오류 발생하는 문제 해결 (focus가 input창에서 나갔을 때 isEdit 조건 확인하여 commentId를 undefined로 설정하지 않도록 수정)
- 대댓글 달 때 부모 댓글에 배경 파란색 주기
- 댓글 내용이 없을 경우 오류 토스트 띄우기 (TOAST constant가 수정되면서 생긴 오류였음)
<br />
| <img width="618" alt="image" src="https://github.com/user-attachments/assets/0e447eee-f04f-463d-bd1b-7247e68f7ac2"> | <img width="619" alt="스크린샷 2024-09-18 오후 5 37 55" src="https://github.com/user-attachments/assets/f46db759-74e8-4563-9e08-2fba5d4f7d67"> |

#400 [FIX] 댓글 관련 오류 해결

---

src/components/Comment/Comment/Comment.jsx
src/components/Comment/NestedComment/NestedComment.jsx
src/components/Modal/DeleteModal.jsx
src/components/Modal/OptionModal.jsx
src/contexts/CommentContext.jsx
src/pages/LoginPage/LoginPage/LoginPage.jsx

close #408
<br />
- 댓글 외부 영역 클릭 시 `commentId`을 undefined로 변경하는 로직 수정
- 기존 event.stopPropagation()을 Comment와 NestedComment 최상위 div로 옮기고, `commentId`을 `undefined`로 설정하는 책임을 CommentContext로 위임
- DeleteModal과 OptionModal 최상위 div에도 event.stopPropagation()을 추가
- 모달이 열렸을 때 아무 영역 클릭 시 CommentContext에 의해 `commentId`가 `undefined`로 set되는 문제를 방지하기 위함
<br />
<br />
- 댓글 수정, 삭제 시 외부 영역을 잘못 클릭하면 `commentId`가 `undefined`로 set 되어 401 에러가 발생했습니다.
- 필요한 경우에만  `commentId`를 `undefined`로 set 하도록 수정해서 버그 해결했습니다.
<br />

#408 [FIX] 댓글 수정, 삭제 버그 해결

---

src/pages/SnoroseVerifyPage/VerifyPage/VerifyPage.jsx

close #418
<br />
- 숙명인 인증 에러 핸들링 로직에서 `error.response.data`의 첫 번째 value를 토스트로 노출하도록 수정
<br />
| <img width="321" alt="image" src="https://github.com/user-attachments/assets/a77753da-309b-4b0d-9231-57bafa4e7191"> |
| 아이디 필드에 학번을 입력하지 않았을 경우 |
<br />

#418 [FIX] 에러 발생 시 빈 토스트가 노출되는 버그 해결

---

src/pages/LoginPage/FindIdPage/inputCheck.js

close #434
<br />
- 회원가입에 생년월일 입력란에 추가 제한을 걸어놨습니다
- Month 입력을 1~12 사이의 숫자로 제한
- Month가 1월, 3월, 5월 7월, 8월, 10월, 12월 일시 Date 입력을 1~31 사이의 숫자로 제한
- Month가 2월, 4월, 6월 9월, 11월 일시 Date 입력을 1~30 사이의 숫자로 제한
- 입력한 생일이 현 날짜를 초과하지 않게 제한
<br />
<br />

#434 [FIX] 생년월일 입력란에 추가 제한 걸어놓기

---

src/route.js

close #454
<br />
- 숙명인 페이지를 감싸는 ProtectedRoute에 권한 설정
- 준회원, 관리자만 접근 가능
<br />

#454 [FEAT] 숙명인 인증 페이지에 준회원 또는 관리자만 접근 가능

---

src/components/Fieldset/TextField/TextField.module.css
src/components/Input/InputItem/InputItem.jsx
src/components/Input/InputItem/InputItem.module.css
src/pages/ExamReviewEditPage/ExamReviewEditPage.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx

close #457
<br />
- 시험후기 상세에서 isOnline 값에 따라 O 또는 X를 보여주게 수정
- 시험후기 작성 및 수정 페이지에서 P/F, 온라인 수업 여부 필드에 필수 마크 삭제
- 시험후기 작성 및 수정 페이지에서 수업명, 교수명 필드에 필수 마크 부여
<br />

#457 [FIX] 시험후기 상세에 누락된 온라인 여부 항목 추가

---

src/components/Modal/Modal.module.css
src/components/PostBar/PostBar.module.css
src/pages/BoardPage/BoardListPage/BoardListPage.module.css

close #484
<br />
- FetchLoading & InputBar와Modal 겹치는 오류 해결 (Modal의 z-index를 101로 높임)
- PostBar에서 줄바꿈 생기는 오류 수정 (렉으로 오류 생긴 것일 수도 있어서 nowrap으로 해결될 지는 모르겠음)
- 한 줄 공지 폰트사이즈 키우기
<br />

#484 [FIX] FetchLoading & InputBar와Modal 겹치는 오류 해결 & 한 줄 공지 폰트사이즈 키우기

---

src/components/Comment/Comment/Comment.jsx
src/constants/modalOptions.js
src/pages/PostPage/PostPage/PostPage.jsx

close #505
<br />
- 만년설방, 시험후기 페이지에서 댓글 삭제 시, 모달에 포인트 관련 내용 안 뜨도록 수정
<br />
<br />

#505 [FIX] 만년설방, 시험후기 페이지에서 댓글 삭제 시, 모달에 포인트 관련 내용 안 뜨도록 수정

---

src/App.module.css
src/index.css
src/pages/BoardPage/BoardPage/BoardPage.module.css

close #518
<br />
- 두번 스크롤 되는 이슈 수정
- 전역에 걸려있는 100vh 스타일 제거 후  html, body, #root에 `height: 100%` 적용 
<br />
- 동일

#518 [FIX] 두번 스크롤 되는 이슈 수정

---

src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.module.css

close #522
<br />
- 시험후기 리스트에 하단 padding 추가 (`6rem`)
<br />
| <img width="325" alt="image" src="https://github.com/user-attachments/assets/edccdf44-6807-4037-8788-89a29967b192"> |
| 시험후기 페이지에서 맨 하단까지 스크롤한 경우 |
<br />

#522 [FIX] 시험후기 마지막 리스트 아이템이 Navbar에 가려지는 문제 수정

---

src/components/InputBar/InputBar.jsx
src/contexts/CommentContext.jsx

close #526
<br />
- 댓글 작성 시에도 commentId를 `undefined`로 초기화
- InputBar를 클릭했을 때 comment context의 value 값이 초기화 되지 않도록 클릭 이벤트에 대해 `event.stopPropagation` 호출
<br />

#526 [FIX] commentId set 문제 수정

---

src/components/AppBar/AppBar/AppBar.module.css
src/components/AppBar/BackAppBar/BackAppBar.module.css
src/components/AppBar/CloseAppBar/CloseAppBar.module.css

기본값으로 두기
close #536
<br />
- AppBar, BackAppBar, CloseAppBar의 z-index css를 삭제
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/44750f6c-8828-4872-8f53-df5c9933ef60"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/5409756d-977e-4a47-8f49-a554c204a67b"> |
<br />

#536 [STYLE] AppBar의 z-index css 삭제

---

src/pages/BoardPage/BoardListPage/BoardListPage.jsx
src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
src/pages/MyPage/ActivityPage/CommentPage.jsx
src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
src/pages/MyPage/ActivityPage/MyPostPage.jsx
src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
src/pages/MyPage/ActivityPage/ScrapPage.jsx
src/pages/MyPage/ViewPointListPage/ViewPointListPage.jsx

close #538
<br />
- pagination이 적용된 페이지에서 isFetching이 `true`일 때 리스트 하단에 FetchLoading 컴포넌트 노출
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/fa4ed146-cb09-4bb1-9256-795b68d3e515"> |
| isFetching=`true` 인 경우 |
<br />

#538 [FIX] pagination 적용된 페이지에 isFetching일 때 리스트 하단에 FetchLoading 컴포넌트 노출

---

src/components/PostBar/PostBar.jsx

close #550
<br />
- 시험후기 리스트 content를 qeustionDetail로 교체
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/965e4ad5-73ec-47be-af92-deec124490be"> |
|  content 대신 questionDetail로 변경 |
<br />

#550 [MODIFY] 시험후기 리스트 content를 qeustionDetail로 교체

---

src/components/Comment/Comment/Comment.jsx
src/components/InputBar/InputBar.jsx

close #562 
<br />
- 댓글 신고 시 input창에 해당 댓글 내용 들어오는 오류 해결 
- 한글 댓글 등록 시 마지막 글자가 Input에 남는 오류 해결
<br />
| <img width="613" alt="image" src="https://github.com/user-attachments/assets/2d92fcb3-dbad-41a7-bdfe-0d89f2c902ad"> | <img width="619" alt="스크린샷 2024-10-06 오후 8 58 23" src="https://github.com/user-attachments/assets/db44e896-2bac-4dae-901a-9b216ff559d7"> |
| 한글 댓글 등록 시 마지막 글자가 Input에 남음 | 해결 완료 |

#562 [FIX] 댓글 신고 시 Input 창에 해당 댓글 들어오는 오류 & 한글 오류 해결

---

src/components/DropDownBlue/DropDownBlue.module.css

close #595
<br />
- DropDownBlue의 z-index 삭제
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/78d30858-bca4-4a68-82a1-1e14494c3ee9"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/8d787e2a-047d-47b1-911d-57878ceea4b3"> |
<br />

#595 [STYLE] DropDownBlue의 z-index 삭제

---

src/components/BoardBar/BoardBar.jsx
src/components/BoardBar/BoardBar.module.css
src/components/BoardCard/BoardCard.module.css
src/constants/boardMenus.js
src/pages/BoardPage/BoardPage/BoardPage.jsx

close #608
<br />
- BoardBar에서 svg 태그를 삭제하고 배경 이미지를 div의 background-image로 삽입
- BoardCard의 desc 너비와 내용 수정
<br />
| <img width="1464" alt="스크린샷 2024-10-10 오전 5 09 40" src="https://github.com/user-attachments/assets/97908466-bed1-428e-a987-d2e7842136d2"> |
| 수정 전 |
| <img width="1464" alt="스크린샷 2024-10-10 오전 5 08 50" src="https://github.com/user-attachments/assets/769c6b0c-0a53-4334-8752-1c59aef5022a"> |
| 수정 후 |
<br />

#608 [FIX] 사파리에서 BoardBar의 배경 이미지가 보이지 않는 문제 수정

---

src/components/Modal/DeleteModal.jsx
src/pages/ExamReviewWritePage/ExamReviewWritePage.jsx

close #612
<br />
- DeleteModal의 primary button 위치를 오른쪽으로 변경
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/a4f9ccd8-b072-4d27-af99-1226e29e551d"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/bd9d667e-dcf0-41a1-a662-09f5fa7c0bd6"> |
<br />
- 시험후기 작성 페이지에서 중복 시험후기 안내 모달의 다운 버튼 클릭 시 모달이 닫히지 않는 문제가 있었습니다.
- ConfirmModal의 `onPrimaryButtonClick` 함수 마지막 줄에 `setIsConfirmModalOpen(false)`을 추가했습니다.
<br />

#612 [REFACTOR] DeleteModal의 primary button 위치를 오른쪽으로 변경

---

src/components/BoardCard/BoardCard.module.css

close #614
<br />
- BoardCard 폰트 사이즈 키우기
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/79814679-bb74-4344-b827-d2f7b2adaeb7"> | <img width="322" alt="image" src="https://github.com/user-attachments/assets/e91cf6ae-3309-4577-8450-f43ce65718ac"> |
<br />

#614 [STYLE] BoardCard 폰트 사이즈 키우기

---

src/apis/login.js
src/pages/LoginPage/FindIdPage/FindIdPage.jsx
src/pages/LoginPage/FindPwPage/FindPwPage.jsx
src/pages/LoginPage/LoginPage/LoginPage.jsx
src/pages/LoginPage/LoginPage/LoginPage.module.css

close #629
<br />
- 버튼을 눌렀을 때 바로바로 다음 화면으로 안 넘어갈 시 유저들이 해당 버튼을 지속적으로 누르는 것이 발견되었다.
그것 때문에 인증번호 메일/비밀번호 찾기 메일이 여러개씩 전송되는 문제가 발생하였다
- 따라서 버튼을 한 번 누르면 비활성화하는 코드를 추가하고, 로딩중일때 로딩중임을 보여주는 FetchLoadingOverlay 사용하기
- 로그인 페이지에서 BackAppBar을 사용할 시, findId나 findPw를 하고 로그인 페이지로 다시 돌아오면
다시는 main페이지로 돌아올 수 없는 상황이 일어나서 그냥 Icon 쓰기로 함
<br />

#629 [FIX] 버튼 한 번 누르면 비활성화하기 & 로딩중 화면 추가

---

src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.jsx
src/pages/ExamReviewPage/ExamReviewDetailPage/ExamReviewDetailPage.module.css

close #634
<br />
- 시험후기 상세에 content 데이터 추가
<br />
| <img width="322" alt="image" src="https://github.com/user-attachments/assets/153dc53c-4e36-4fab-8df6-dd1c81991773"> |
| content가 추가된 시험후기 상세 |
<br />

#634 [MODIFY] 시험후기 상세에 content 내용 추가

---

src/apis/login.js
src/pages/LoginPage/FindIdPage/FindIdPage.jsx
src/pages/LoginPage/FindPwPage/FindPwPage.jsx
src/pages/LoginPage/FindPwPage/FindPwPage.module.css
src/pages/LoginPage/SignUpPage/SignUpPageStages/AccountInfoPage.jsx

close #631
<br />
- 아이디 찾기에서 사용자에게 이메일을 입력 받지 않고 서버에 저장된 이메일로 아이디 발송
- 아이디 찾기 이메일 필드 삭제
- 결과 페이지에 서버 응답으로 받은 이메일 노출
- 비밀번호 찾기 페이지에 안내 사항 추가
- "메일" 문구를 "이메일"로 바꿈
<br />

#631 [MODIFY] 아이디 찾기에서 이메일 필드 삭제하고, 서버 응답으로 받은 이메일을 보여주기

---

src/components/Carousel/Slide/Slide.jsx

배너 랜딩 URL이 외부 링크인 경우가 있어 수정했습니다.
close #639
<br />
- 배너 랜딩 URL이 외부 링크인 경우가 있어서 Slide 컴포넌트에서 Link를 a 태그로 변경했습니다.
<br />

#639 [CHORE] Slide에서 Link를 a 태그로 변경

---

src/pages/LoginPage/FoundIdPage/FoundIdPage.jsx
src/pages/LoginPage/FoundPwPage/FoundPwPage.jsx
src/pages/LoginPage/NotFoundIdPage/NotFoundIdPage.jsx
src/pages/LoginPage/NotFoundPwPage/NotFoundPwPage.jsx

close #641
<br />
- 아이디 찾기, 비밀번호 찾기에서 상단 앱바의 뒤로가기 버튼 클릭 시 로그인 페이지로 이동하도록 수정 
<br />

#641 [MODIFY] 아이디 찾기, 비밀번호 찾기에서 상단 앱바의 뒤로가기 버튼 클릭 시 로그인 페이지로 이동하도록 수정

---

src/components/PostBar/PostBar.jsx

close #644
<br />
- 시험후기 PostBar에서 questionDetail이 우선하여 보여지도록 Nullish coalescing 연산에서 인자 순서 변경
<br />

#644 [MODIFY] questionDetail을 먼저 검사해서 시험후기 PostBar에서 우선 순위로 노출하도록 변경

---

src/ProtectedRoute.jsx
src/index.css

close #661
<br />
- ProtectedRoute 로그인 접근 제한 로직 위로 올리기
- 애드센스가 자동으로 삽입하는 padding을 무시하기 위해 body에 padding: 0 강제
<br />

#661 [FIX] ProtectedRoute 로그인 접근 제한 및 애드센스가 자동으로 삽입하는 padding 무시

---

src/components/index.js
src/constants/reactQuery.js
src/hooks/usePagination.jsx
src/hooks/useScrollRestoration.js
src/hooks/useSearch.jsx
src/pages/BoardPage/BoardListPage/BoardListPage.jsx
src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
src/pages/BoardPage/index.js
src/pages/ExamReviewPage/ExamReviewPage/ExamReviewPage.jsx
src/pages/MyPage/ActivityPage/CommentPage.jsx
src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
src/pages/MyPage/ActivityPage/MyPostPage.jsx
src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
src/pages/MyPage/ActivityPage/ScrapPage.jsx

close #682
<br />
- 페이지네이션에 staleTime 적용
- 상세 페이지 접속 시 session storage에 PAGINATION_CACHE_SESSION 추가
- 세션 스토리지에 PAGINATION_CACHE_SESSION이 없으면 페이지네이션 쿼리 reset
<br />
| ![GIFMaker_me](https://github.com/user-attachments/assets/eecf65cb-cb72-4a93-8765-eb3fcc97787f) |
| 수정 전 |
| ![GIFMaker_me2](https://github.com/user-attachments/assets/cbc66392-b316-431d-86f0-6f4a6426c8b9) |
| 수정 후 |
<br />

#682 [PERF] 페이지네이션 API 호출 최적화

---

src/hooks/usePagination.jsx

close #698
<br />
- usePagination 훅의 useEffect에서 `hasNextPage`, `isFetching` 의존성 제거
<br />
| ![2024-10-1510 46 18-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/06f7eb60-437a-4703-bd14-02480972b81a) |
| 수정 전 |
| ![2024-10-1510 45 39-ezgif com-optimize](https://github.com/user-attachments/assets/014e9c06-978b-42bd-b8f1-0e438a790f07) |
| 수정 후 |
<br />

#698 [PERF] 페이지네이션 fetch 페이지 수 개선

---

src/components/ReviewDownload/ReviewDownload.jsx

close #701
<br />
- 시험후기 파일명에 타임스탬프 추가하는 로직 변경
- .(dot)을 기준으로 split 하는 대신 `.pdf`를 `_타임스탬프.pdf`로 replace
- 시험후기 파일명을 변경하는 로직을 `appendTimestampToFileName` 함수로 추출
<br />

#701 [FIX] 다운로드 된 시험후기 파일명이 잘리는 문제 수정

---

src/components/InputBar/InputBar.jsx
src/hooks/useComment.jsx

close #703
<br />
- useComment에 api의 로딩 상태를 나타내는 `loading` state를 추가했습니다.
- `loading` state를 InputBar의 `submitComment`에 연결해서 `true`이면 api를 호출하지 않고 함수를 종료하도록 early return 했습니다.
<br />

#703 [FIX] 댓글 작성 및 수정에 대한 다중 api 요청 방어

---

src/components/PostList/PostList.jsx
src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
src/pages/MyPage/ActivityPage/CommentPage.jsx
src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
src/pages/MyPage/ActivityPage/MyPostPage.jsx
src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
src/pages/MyPage/ActivityPage/ScrapPage.jsx
src/utils/pagination.js

close #710
<br />
- 페이지네이션 데이터에서 중복 데이터를 제거하는 `deduplicatePaginatedData` 함수 구현
- 게시글 페이지네이션 데이터 평탄화 로직에 `deduplicatePaginatedData` 적용
<br />

#710 [FIX] 게시글 pagination data에서 postId가 중복인 게시글을 걸러냄

---

src/components/PostList/PostList.jsx
src/pages/BoardPage/BoardListPage/BoardPostList/BoardPostList.jsx
src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
src/pages/ExamReviewPage/ExamReviewSearchList/ExamReviewSearchList.jsx
src/pages/MyPage/ActivityPage/CommentPage.jsx
src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
src/pages/MyPage/ActivityPage/MyPostPage.jsx
src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx
src/pages/MyPage/ActivityPage/ScrapPage.jsx

close #711
<br />
- 게시글 페이지네이션 데이터 평탄화 로직을 @/utils/pagination.js에 있던 `flatPaginationCache` 함수로 교체
```js
// 리팩터링 전
const postList =
data && !data.pages.includes(undefined)
? deduplicatePaginatedData(data.pages.flatMap((page) => page.data))
: [];
// 리팩터링 후
const postList = deduplicatePaginatedData(flatPaginationCache(data));
```
<br />

#711 [REFACTOR] 게시글 페이지네이션 데이터 평탄화 로직을 함수로 교체

---

src/pages/ExamReviewPage/ExamReviewList/ExamReviewList.jsx
src/pages/MyPage/ActivityPage/DownloadExamReviewPage.jsx
src/pages/MyPage/ActivityPage/ScrapExamReviewPage.jsx

close #719
<br />
- ExamReviewList, DownloadExamReviewPage, ScrapExamReviewPage에서 deduplicatePaginatedData에 대한 중복 import를 제거했습니다.
<br />

#719 [FIX] deduplicatePaginatedData에 대한 중복 import로 인해 발생한 컴파일 에러 문제 수정

---

src/pages/PostPage/PostPage/PostContent.jsx

close #732
<br />
- url 매치 정규표현식 수정
- 수정 전엔 whitespace 빼고 모든 문자 매치 가능
- 수정 후엔 [a-zA-Z0-9._/] 안에서만 매치 가능
<br />
| <img width="323" alt="image" src="https://github.com/user-attachments/assets/a9db7792-f7b3-437d-8b2c-d35b72a6c6fc"> | <img width="323" alt="image" src="https://github.com/user-attachments/assets/5adf78ff-a116-40a6-8f4b-b63b2efaf97d"> |
| 하이퍼링크 수정 전 | 하이퍼링크 수정 후 |
<br />

#732 [FIX] URL 바로 뒤에 오는 문자들도 하이퍼링크로 인식하는 버그 수정

---

src/components/Sidebar/Sidebar/Sidebar.module.css

close #754
<br />
- 홈화면 배너와 사이드바 겹침 이슈 해결을 위해 사이드바 z-index를 10으로 수정
<br />
| <img width="250" src="https://github.com/user-attachments/assets/48654646-5bde-4aee-9432-b3bd09d0d7ff" />|<img width="250" src="https://github.com/user-attachments/assets/c6ce2150-d79c-426e-9140-a13a3b21d1e7" />|
| :---------------------: |:---------------------: |
| 이전 | 이후 |

#754 [FIX] 홈화면 배너와 사이드바 겹침 이슈 해결을 위해 사이드바 z-index를 10으로 수정

---

src/components/PopUp/Component.jsx
src/components/PopUp/Component.module.css
src/components/PopUp/PopUp.jsx
src/components/PopUp/PopUp.module.css

close #768
<br />
- 팝업 공지에서 리뉴얼 만족도 조사 안내 삭제
- 팝업 컴포넌트에서 사용하는 제목, 내용 태그를 Heading, Content 컴포넌트로 분리
<br />

#768 [CHORE] 팝업 공지에서 리뉴얼 만족도 조사 안내 삭제

---

src/apis/examReview.js

close #782
<br />
- 시험후기 수정 api 호출 시 수정 데이터를 param이 아니라 request body로 전달하도록 수정
<br />
| <img width="706" alt="image" src="https://github.com/user-attachments/assets/f73209bf-872f-485d-aeb2-151c80c3f250" /> |
<br />

#782 [FIX] 시험후기 api 요청 시 수정 데이터를 param이 아니라 request body로 전달하도록 수정

---

package-lock.json
package.json
src/App.jsx
src/components/DropDownBlue/DropDownBlue.module.css
src/components/MenuIcon/MenuIcon.jsx
src/components/Sidebar/List/List.jsx
src/components/Sidebar/List/List.module.css
src/components/Sidebar/Sidebar/Sidebar.jsx
src/components/Sidebar/Sidebar/Sidebar.module.css
src/components/index.js
src/stores/index.js
src/stores/useSidebarStore.js

close #779
<br />
- 시험후기 필터의 z-index를 1로 설정했습니다.
- 사이드바보다 시험후기 필터의 쌓임 맥락이 더 위에 있어서 시험후기 필터가 사이드바 위로 올라오는 문제를 사이드바를 MenuIcon에서 App 컴포넌트로 끌어올려 해결했습니다.
- 이 과정에서 사이드바의 상태 관리에는 zustand를 사용했습니다.
- 사이드바 메뉴의 클릭 영역을 padding을 통해 키우고, 어떤 메뉴를 active 중인지 가시적으로 보여주기 위해 hover 상태에 color를 추가했습니다.
<br />
| <img width=320 src=https://github.com/user-attachments/assets/a614786b-a25d-4e9a-89f1-6936aa336ce7 /> | <img width=320 src=https://github.com/user-attachments/assets/beb8b792-4d03-4b73-ad67-480bcfaffdf6 /> |
| 사이드바 `hover` | 시험후기 필터 |
<br />

#779 [FIX] 시험후기 필터가 pull refresh 시 다른 UI 뒤로 숨는 문제 해결

---

src/components/PopUp/PopUp.jsx
src/components/PopUp/PopUp.module.css
src/hooks/usePopUp.jsx
src/pages/MainPage/MainPage.jsx
src/utils/date.js

close #791 
<br />
- `usePopUp` 훅 의존성을 MainPage에서 `PopUp` 컴포넌트로 옮겼습니다.
- 매개변수로 전달한 `date`와 숫자를 더해서 새로운 날짜를 반환하는 `addDays` 유틸 함수를 추가했습니다.
- 팝업 보지 않기 버튼을 checkbox에서 라디오 버튼으로 변경했습니다.
- 팝업 3일간 보지 않기 버튼을 추가했습니다.
<br />
| <img width="1470" alt="image" src="https://github.com/user-attachments/assets/99615aec-a7a9-4107-87ae-2e447fb7835c" /> |
<br />

#791 [FEAT] 팝업 3일간 보지 않기

---

src/components/Comment/Comment/Comment.jsx
src/components/Comment/Comment/Comment.module.css
src/components/Comment/NestedComment/NestedComment.jsx
src/pages/PostPage/PostPage/PostContent.jsx
src/utils/hyperlink.js
src/utils/index.js

close #790
<br />
- `PostContent` 컴포넌트에서 사용중인 URL에 a 태그를 감싸는 `replace` 함수를 `convertHyperlink`라는 유틸 함수로 분리했습니다.
- `Comment`와 `NestedComment` 컴포넌트의 댓글 내용에 `convertHyperlink` 함수를 사용하여 하이퍼링크를 활성화했습니다.
<br />
| <img width="1470" alt="스크린샷 2025-01-03 오후 5 38 31" src="https://github.com/user-attachments/assets/3cbff932-de3c-4bad-9458-f996537bae04" /> |
<br />

#790 [FEAT] 댓글 하이퍼링크 활성화

---

src/components/PostBar/PostBar.jsx
src/pages/PostPage/PostPage/PostPage.jsx
src/utils/date.js

close #786
<br />
- 게시판 날짜 표기 방식 변경
- 1시간 이내: '00분 전' 또는 '00초 전'
- 오늘 날짜인 경우: '16:24'
- 같은 연도 다른 날짜: '12/28 16:24'
- 다른 연도: '23/12/28 16:24'
<br />
<br />

#786 [FEAT] 게시판 날짜 표기 방식 변경

---

src/assets/icon.svg
src/pages/PostPage/PostWritePage/PostWritePage.module.css

close #813
<br />
- 누락된 `toggle-on`, `toggle-off` 아이콘 추가
<br />
| <img width="599" alt="image" src="https://github.com/user-attachments/assets/34d6e6f0-fe92-4d21-a9ce-971b4c01ee54" /> |
<br />

#813 [FIX] 게시글 작성 페이지에서 공지글 토글 버튼이 노출되지 않는 문제 해결

---

src/components/Search/Search.jsx
src/pages/NoticeListPage/NoticeListPage.jsx
src/pages/PostsPage/PostsPage.jsx
src/pages/SearchPage/SearchPage.jsx

close #826
<br />
- `SearchPage`의 `BackAppBar`에서 현재 라우트에 따라 `backNavTo`를 분기 처리하지 않고, 항상 **이전 페이지**로 이동할 수 있도록 `Search` 컴포넌트의 `setSearchParams`에 replace 옵션을 `true`로 설정했습니다.
- 게시판 페이지와 공지 페이지는 뒤로가기 버튼 클릭 시 항상 이전 히스토리로 이동해야 하므로 `backNavTo` prop을 제거했습니다.
<br />

#826 [FIX] BackAppBar 히스토리가 비정상적으로 동작하는 문제 수정

---

src/feature/home/component/PopUp/PopUp.module.css
src/page/board/PostPage/PostPage.jsx

close #848 
<br />
- 게시글 내용이 작게 보이는 오류 수정
- 팝업창의 이미지로 인한 좌우 스크롤 문제 수정
<br />
| ![스크린샷_게시글](https://github.com/user-attachments/assets/406ebfce-0d2b-4128-afa3-ac547f967ffc) |
| ![스크린샷_팝업](https://github.com/user-attachments/assets/f298907c-2a88-4cf7-9ff4-2c5f8f93fb35) |
<br />
- PostPage에서 css 이름 지정 오타 수정 (content -> contentText)
- Popup 이미지 스크롤 생기는 문제를 img태그 max-width 지정
<br />

# 848 [FIX] 팝업 공지 좌우 스크롤 이슈 및 게시글 폰트가 비정상적으로 작은 문제 수정

---

src/feature/my/component/MyPostList/MyPostList.jsx
src/feature/my/component/MyPostList/MyPostList.module.css
src/feature/my/constant/activity.js

close #799
<br />
- 마이페이지 - 내 활동 탭 내 항목별 빈 상태 일러스트 적용
<br />
| 내가 쓴 글 | 댓글 단 글 모아보기 | 다운 받은 시험 후기 모아보기 |
| :---------------------: |:---------------------: |:---------------------: |
| <img width='250' src='https://github.com/user-attachments/assets/e03bac1a-2b06-4afd-90f4-64c3b79b8dc0' /> |  <img width='250' src='https://github.com/user-attachments/assets/1678ad0d-cd90-47ec-8002-1c3d01efd325' /> |  <img width='250' src='https://github.com/user-attachments/assets/a9df8250-36af-4f1a-89b1-314ae6073d86' /> |
| 시험 후기 스크랩 | 스크랩 모아보기 |
| :---------------------: |:---------------------: |
| <img width='250' src='https://github.com/user-attachments/assets/21746c6a-499f-4a51-bfa1-786bc4770c39' /> |  <img width='250' src='https://github.com/user-attachments/assets/8b9c8fbb-d033-4a37-b0dd-48c5f725705 …

#799 [FIX] 현재 게시판에 따른 일러스트 이미지 적용

---

src/feature/exam/constant/exam.js

close #913
<br />
- 시험후기 작성 페이지에서 연도 옵션에 2025를 추가합니다.
<br />

#913 [CHORE] 시험후기 작성 연도 옵션에 2025 추가

---

src/shared/component/layout/Sidebar/Sidebar.module.css

close #917
<br />
- sidebar에 `overflow-y: auto` 적용해서 스크롤 가능하게 변경했습니다.
- logo에 `position: sticky; top: 0` 적용해서 로고는 상단에 고정하도록 수정했습니다.
- 사이드바 상단 padding을 로고 padding-top으로 옮기고, logo 하단 margin을 padding으로 변경하여 로고 뒤로 스크롤 되는 메뉴들을 여유있게 가려주었습니다.
<br />

[FIX] 뷰포트 높이가 작아지는 경우 사이드바 내용이 화면 밖으로 넘치는 문제 해결

---

src/assets/icon.svg

Close #996
- icon.svg에 meat-ball 아이콘 추가
|   <img width="607" alt="스크린샷 2025-05-22 오후 11 15 43" src="https://github.com/user-attachments/assets/0b7c4bbc-65fd-475b-a97a-918c88dcd882" />     |    <img width="547" alt="스크린샷 2025-05-22 오후 11 13 59" src="https://github.com/user-attachments/assets/2268f015-c66d-4886-b40f-d7b036d6845e" />   |
- 예전에 PostPage 작업할 때 icon.svg에 meat-ball 아이콘도 추가했었는데
- 작업 중간에 누락되거나, conflict 해결 과정에서 날라간 것 같네요.
- 다시 추가해서 오류 해결했습니다.

#996 [SNO-101] PostPage에서 내가 쓴 게시물에 점 세 개 아이콘 안 뜨는 오류 해결

---

src/apis/post.js

Close #1016 
- 게시글 수정 API 스펙 변동됨
- request body에 `createAttachment` -> `finalAttachment` 속성명 변경됨
- 이로 인해 현재 게시글 수정에서 400에러가 나고 있었음
- 속성명 변경해서 오류 해결 완

#1016 [SNO-89] 게시글 수정 API 스펙 변동으로 인한 400 에러 해결 

---

src/apis/attendance.js
src/apis/index.js
src/apis/point.js
src/page/home/AttendancePage/AttendancePage.jsx
src/page/home/AttendancePage/AttendancePage.module.css
src/router.js
src/shared/component/loading/FetchLoadingOverlay/FetchLoadingOverlay.module.css
src/shared/loader/attendance.js
src/shared/loader/index.js

Close #1038
- [Notion-제언](https://www.notion.so/snorose/1ea7ef0aa3bf8150b075dfcb045d1592?source=copy_link)
- `router.js`의 출석체크 페이지에서 loader를 추가해서 출석체크 페이지 접근 전 오늘의 출석 여부 데이터를 fetch합니다.
```js
// router.js
...
{
path: '/attendance',
element: <AttendancePage />,
loader: attendanceLoader,
meta: {
hideNav: true,
},
},
...
```
```js
// attendance loader
export const attendanceLoader = async () => {
const attendance = await isAttendanceCheckedToday();
return json({ attendance });
};
```
- AttendanceButton에서 useLoaderData로 출석 여부 데이터를 가져와 `isAttendance` state를 초기화 합니다.
```jsx
const { attendance } = useLoaderData();
const [isAttendance, setIsAttendance] = useState(attendance);
```
- 출석체크 성공 시 `isAttendance`을 `true`로 업데이트 합니다.

#1038 [SNO-112] 출석 상태에 따라 버튼 메시지 분기 (제언)

---

src/feature/exam/lib/CheckExamPeriodRoute.jsx
src/page/exam/WriteExamReviewPage/WriteExamReviewPage.jsx

Close #926
- CheckExamPeriodRoute의 useEffect 의존성 배열에 `userInfo`를 추가하고, `userInfo`가 undefined인 경우 ealry return 하도록 수정했습니다.
```jsx
useEffect(() => {
if (!userInfo) return;
// ...
}, [userInfo]);
```
- 시험후기 작성 페이지에서 변경된 내용이 없는 경우에도 페이지 이탈 방지 모달이 노출되는 버그가 있어 수정했습니다.
- `lectureType`, `examType`, `lectureYear`, `semester`의 경우 아무것도 선택되지 않았음에도 `{}` 빈 객체가 기본값으로 세팅되기 때문에 `isBlock`이 default로 Truthy가 되는 문제 수정
```jsx
const isBlock = !!(
lectureName.trim() ||
professor.trim() ||
Object.keys(lectureType).length > 0 ||
Object.keys(examType).length > 0 ||
Object.keys(lectureYear).length > 0 ||
Object.keys(semester).length > 0 ||
classNumber ||
questionDetail.trim() ||
file
);
```
|        |       |

#926 [SNO-121] 시험후기 작성 페이지 undefined 참조 오류 해결

---

public/index.html

Close #1068 
- 현재 모바일에서 Status Bar가 어두운 색이라 스노로즈 기본 바탕색인 흰색과 연결이 안 되어 어색함
- meta 태그를 수정해 기본 색상을 흰색으로 지정
| <img width="1170" height="2532" alt="image" src="https://github.com/user-attachments/assets/de8e256b-6cfc-4686-ae72-3b274660c098" /> | <img width="1170" height="2532" alt="image" src="https://github.com/user-attachments/assets/7dc99c59-97bf-41e1-8f44-f72330503b5e" /> |
- prettier 때문에 파일 수정이 많은 것처럼 나왔는데 실제로는 아래 코드만 수정됐으니 참고바랍니다.
```javascript
// Before
<meta name="theme-color" content="#000000" />
// After
<meta name="theme-color" content="#ffffff" />
```

#1068 [SNO-131] 모바일 Status Bar 색상 흰색으로 수정

---

src/feature/home/component/PopUp/PopUp.module.css
src/shared/component/layout/AppBar/AppBar.module.css
src/shared/component/layout/Sidebar/Sidebar.module.css
src/shared/component/modal/Modal.module.css

Close #1080
- 상단 앱바보다 높게 표시되던 필터, 모달창을 수정했습니다.
| <img width="200"  alt="image" src="https://github.com/user-attachments/assets/6fb5c64a-48bc-419a-aad4-32ac6725dd93" /> | <img width="200" alt="image" src="https://github.com/user-attachments/assets/6022c0b8-f2d0-44fa-a0dc-a243d2b38fc0" /> <img width="200" alt="image" src="https://github.com/user-attachments/assets/c2c0f63d-eba9-4c56-8de6-a1ae28623b94" /> |
- 담당페이지가 아닌 부분을 수정했어서, 혹시 `z-index` 관련해서 놓친 부분이 있다면 알려주세요 :)
- [기존 이슈 공유]
홈화면이 아닌 페이지 (ex. 게시판, 시험후기)에서 사이드바를 열었다가 홈화면으로 이동할 경우, 
팝업창과 사이드바가 겹쳐보이는 이슈가 있어요~ 
팝업창을 닫으면 사이드바가 바로 사라지기는 하지만, 해당 이슈는 이번 PR이 아닌 새로운 액션 아이템으로서 작업이 필요해 보여요 :)

#1080 [SNO-134] 시험후기 게시판 z-index 수정

---

src/shared/component/layout/Footer/Footer.jsx
src/shared/component/layout/Footer/Footer.module.css
src/shared/constant/toast.js

Close #1088 
홈 화면 Footer에 있는 후원 계좌를 클릭하면 계좌번호가 자동으로 복사되는 기능을 구현했습니다.
스노로즈에는 우클릭 기능이 제한되어 있어, 후원 계좌번호를 간편하게 복사할 수 있도록 클릭 시 자동 복사 기능을 추가하게 되었습니다.
| 복사 성공 | 복사 실패 |
| <img width="400" alt="image" src="https://github.com/user-attachments/assets/9feefcc7-72b0-45c8-844e-204acb195484" /> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/3aacab23-c2da-4fec-9cc2-1c943f53c17c" />|
- 실패 케이스 UI 확인 방법 
```
// 콘솔에 붙여넣어 실행 후, 후원 계좌 클릭
navigator.clipboard.writeText = () => Promise.reject(new Error('강제 실패'));
```
- 성공 메시지와 실패 메시지 구분을 위해 이모지를 넣었어요.
스노로즈는 성공과 실패의 UI가 동일해 토스트 메시지만으로는 직관적인 전달이 어려운 부분이 있어요.
아래에 Toss 사례를 함께 첨부했는데, 추후 이런 부분에 대해서도 함께 고민해보면 좋을 것 같아요 :)

#1088 [SNO-140] 홈 화면 하단 계좌번호 선택시 복붙 기능

---

src/page/board/PostPage/PostPage.jsx
src/page/board/PostPage/PostPage.module.css

Close #1103
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8---1%EC%B0%A8-%EA%B0%9C%EB%B0%9C?node-id=5332-14791&m=dev)
아이콘 변경 전에 iPhone 12 Pro에서는 좋아요 수가 1,000개 이상일 때 줄바꿈 이슈가 있었습니다. [Notion 참고](https://www.notion.so/snorose/1000-2337ef0aa3bf8018a7cce3ab3e411dce?source=copy_link)
아이콘 변경 후에 해당 디바이스에서 나타나는 이슈는 해결되었지만, SE 버전에서는 여전히 줄바꿈이 발생하고 있습니다. 
Figma 기준으로는 공감 수가 3자리일 때 gap이 `2.5rem`으로 설정되어 있어 gap 크기를 줄였습니다. (hover 효과도 있어 해당 gap 유지가 필요해 보입니당)
크게 눈에 띄는 이슈는 아니지만, 이슈라이징 된 김에 수정해두었어요 :)
|  <img width="281" height="500" alt="image" src="https://github.com/user-attachments/assets/79d305e6-ab34-4693-bcdb-81cfb4d02821" />| <img width="281" height="500" alt="image" …

#1103 [SNO-136] 공감 줄바꿈으로 인한 gap 조정

---

src/feature/comment/hook/useComment.jsx

Close #1118
- 댓글 등록 및 삭제 시 화면이 하얗게 깜빡이는 이슈가 있어 해결 했습니다. (수정은 정상)
- Before
https://github.com/user-attachments/assets/f797004d-91c5-459a-8004-f9670c68d3b8
- After
https://github.com/user-attachments/assets/a5cac144-a2b9-4e99-808f-f1430cf7d8a6
- QA할 때, 포인트가 실시간으로 업데이트 되는지 함께 확인해 주시면 좋을 것 같아요 :)
- 이슈 원인
`invalidUserInfoQuery()` 호출로 `userInfo` 쿼리가 전역 무효화되어 리패치가 발생했고, 이 과정에서 화면이 일시적으로 로딩(Suspense) 상태로 전환되며 하얀 화면(깜빡임)이 노출되었습니다.
- 해결 방법
- `invalidUserInfoQuery()` 제거(전역 리페치 중단).
- `onSuccess`에서 부분 캐시 갱신만 수행:
- `setQueryData([comments, postId], …)`로 댓글 목록 갱신
- `setQueryData([post, postId], …)`로 `commentCount` 증감 처리

#1118 [SNO-156] 댓글 등록 및 삭제 시 화면 깜빡거리는 이슈 해결

---

src/ProtectedRoute.jsx
src/shared/component/Modal/NoticeModal/NoticeModal.jsx
src/shared/component/Modal/NoticeModal/NoticeModal.module.css
src/shared/component/index.js
src/shared/constant/modalText.js

Close #1144
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/-%EC%8A%A4%EB%85%B8%EB%A1%9C%EC%A6%88--%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8?node-id=5604-11619&m=dev)
- 단일 버튼 모달인 `NoticeModal` 컴포넌트를 추가하고 인증 페이지에 적용  
- 기존 모달에서 `예` 버튼 클릭 시 `verify` 페이지로 무한 루프에 빠지는 문제가 있어, 버튼이 동작하지 않는 것처럼 보이는 이슈가 있었습니다.
| <img width="250"  alt="image" src="https://github.com/user-attachments/assets/60c5a918-aa5c-46c5-b49c-d6d5c805b47b" /> |  <img width="250"  alt="image" src="https://github.com/user-attachments/assets/041044a4-f407-4ba7-9088-e922b88426fe" /> |

#1144 [SNO-182] 단일 버튼 모달인 NoticeModal 컴포넌트 추가 및 인증 페이지에 적용

---

src/feature/account/component/snoroseVerifyStep/VerifyStep/VerifyStep.module.css

Close #1147
- [Discord](https://discord.com/channels/1218891487312351283/1223646189413466124/1414423380337360916)
- 인증 페이지 스크롤 이슈 해결
- 해당 페이지는 다른 페이지와 달리 컨텐츠가 많아, 디바이스의 화면 높이에 따라 인증 버튼이 이메일 입력창을 가리는 이슈가 발생했습니다.
- 컨텐츠와 버튼 사이에 `gap` 속성을 적용했습니다.
|  <img width="250"  alt="image" src="https://github.com/user-attachments/assets/3f5fe79e-08fa-4fd3-a65a-c50d00b9d598" />|<img width="250"  alt="IMG_4176" src="https://github.com/user-attachments/assets/898b0974-16ad-40e4-8a78-185b16d38a1d" />|

#1147 [SNO-183] 인증페이지에서 스크롤 안되는 이슈 해결

---

src/assets/images/blackCloudLogo.svg
src/assets/images/cloudLogo.svg
src/feature/board/component/PostBar/PostBar.jsx
src/feature/board/component/PostBar/PostBar.module.css
src/feature/comment/component/Comment/Comment.jsx
src/feature/comment/component/Comment/Comment.module.css
src/feature/comment/component/CommentInput/CommentInput.jsx
src/feature/comment/component/CommentInput/CommentInput.module.css
src/feature/comment/component/NestedComment/NestedComment.jsx
src/feature/home/component/AccordionListItem/AccordionListItem.jsx
src/feature/home/component/AccordionListItem/AccordionListItem.module.css
src/page/board/BoardCategoryPage/BoardCategoryPage.jsx
src/page/board/BoardCategoryPage/BoardCategoryPage.module.css
src/page/board/EditPostPage/EditPostPage.jsx
src/page/board/EditPostPage/EditPostPage.module.css
src/page/board/PostPage/PostPage.jsx
src/page/board/PostPage/PostPage.module.css
src/page/board/WritePostPage/WritePostPage.jsx
src/page/board/WritePostPage/WritePostPage.module.css
src/page/exam/ExamReviewPage/ExamReviewPage.jsx
src/page/exam/ExamReviewPage/ExamReviewPage.module.css
src/shared/component/PullToRefresh/PullToRefresh.jsx
src/shared/component/PullToRefresh/PullToRefresh.module.css
src/shared/component/loading/FetchLoading/FetchLoading.jsx
src/shared/component/loading/FetchLoading/FetchLoading.module.css

Close #1174
- 로고를 단일 파일로 교체하고 관련 페이지를 수정했습니다.
아이폰 iOS 26 버전에서 네이버, 사파리, 크롬 등 일부 브라우저에서 로고가 표시되지 않는 문제가 있었는데, 아이콘 내 그라데이션 처리로 인해 발생한 이슈로 보입니다. 이를 해결하기 위해 단일 파일 로고로 교체하는 작업을 진행했습니다.
| <img width="200"  alt="IMG_4248" src="https://github.com/user-attachments/assets/a9424f8d-60fc-4d37-8228-19baf3a4a3e2" /><img width="200"  alt="IMG_4247" src="https://github.com/user-attachments/assets/2b57e9c8-b30f-46d7-b467-be22c12fc6d7" /> | <img width="200"  alt="IMG_4245" src="https://github.com/user-attachments/assets/1ab23d66-a985-4b40-a22f-30fc55eeb81a" /><img width="200"  alt="IMG_4246" src="https://github.com/user-attachments/assets/9a37d3c2-82a9-4983-99f7-a9bb4f003e9f" /> |
- 기존에도 PC에서 이슈는 없었던터라, 모바일 환경 네이버, 사파리, 크롬 등 브라우저에서 확인해 주시면 좋을 것 같아요 :)
- `dev` 브랜치에서 …

#1174 [SNO-199] 로고 단일 파일로 교체 및 관련 페이지 수정

---

src/App.jsx
src/apis/alert.js
src/feature/alert/lib/PushNotification.js
src/shared/component/layout/Navbar/Navbar.jsx
src/shared/constant/reactQuery.js

Close #1176
- [Notion](https://www.notion.so/snorose/26d7ef0aa3bf802aab6ce6c491a9fbfe?source=copy_link)
- 안 읽은 알림 개수 조회를 react query로 캐싱
- PushNotification 클래스에 onForegroundMessage 콜백 등록 함수 생성
- App.jsx에서 `onForegroundMessage`를 호출하여 알림 관련 캐시 데이터 무효화 로직 등록
- 무효화 대상은 알림함 및 안 읽은 알림 개수
- FCM 토큰이 있어야 제대로 된 테스트가 가능합니다. 모바일에서 테스트해주세요.
- 불가피하게 PC로 테스트 해야하는 경우 임의로 가드를 꺼주시기 바랍니다.

#1176 [SNO-200] 알림함 및 안 읽은 알림 개수 실시간 동기화

---

src/feature/alert/hook/notification.js

Close #1185
- [Figma]()
- [Notion]()
알림 설정을 변경한 뒤 설정 페이지를 다시 열면, UI가 최신 상태가 아니라 이전 상태를 그대로 보여주는 문제가 있었습니다.
한 번 더 페이지를 나갔다 들어와야만 최신 상태가 반영되었습니다.
- mutation의 onSettled에서 `refetchType: 'inactive'`를 사용해, 알림 설정 변경 직후 쿼리가 갱신되지 않았습니다.
- 또한 쿼리 데이터를 리듀서 초기값으로만 사용하고 있기 때문에, refetch가 일어나더라도 리듀서 상태가 갱신되지 않아 UI는 이전 상태를 계속 바라보게 되었습니다.
`refetchType` 옵션을 제거해 기본값(`'active'`)으로 동작하도록 수정했습니다. 이제 알림 설정 변경 후 쿼리가 즉시 refetch되어, UI와 캐시가 일관된 최신 상태를 보여주게 됩니다.

#1185 [SNO-201] 알림 설정 쿼리가 갱신되지 않는 문제 해결

---

src/feature/alert/hook/notification.js

Close #1178
- [Notion](https://www.notion.so/snorose/26d7ef0aa3bf805abbc0fb45d0651328?source=copy_link)
- 알림 모두읽기 시 클라이언트 단에서 미확인 알림 개수를 0으로 바꾸고, 클라이언트 값을 서버 데이터에 맞춰 동기화 하기 위해 `queryClient.invalidateQueries`를 추가했습니다.
- `queryClient.invalidateQueries`를 onSettled에서 호출했음에도 백엔드에서 최신 데이터가 아닌 이전 데이터를 내려주어서 refetchType: 'inactive'으로 지정했습니다.

#1178 [SNO-206] 알림 모두읽기 시 미확인 알림 개수가 실시간으로 동기화 되지 않는 이슈 해결

---

src/feature/search/component/Search/Search.module.css
src/page/alert/AlertPage/AlertPage.module.css
src/page/board/PostListPage/PostListPage.jsx
src/page/board/PostListPage/PostListPage.module.css
src/page/exam/ExamReviewListPage/ExamReviewListPage.jsx
src/page/exam/ExamReviewListPage/ExamReviewListPage.module.css

Close #1240
- [Figma](https://www.figma.com/design/00Ywy8VC5KoHOSu01uC9sZ/-%EC%8A%A4%EB%85%B8%EB%A1%9C%EC%A6%88--%EC%9C%A0%EC%A0%80%EC%9B%B9-%EB%94%94%EC%9E%90%EC%9D%B8?node-id=4279-13125&m=dev)
- 공지 컴포넌트
- 상하 padding 값을 적용하고, 줄바꿈 시 글자가 넘어가면 '...'으로 표시되도록 CSS 속성 추가
- 알림 페이지 내 bell 아이콘 크기와 동일하게 수정
- 검색창 컴포넌트
- 공지 컴포넌트와 폰트 사이즈 동일하게 수정 
- 공지 컴포넌트와 좌우 padding 값 동일하게 수정
-> 공지와 검색창 컴포넌트의 `폰트 사이즈`, `padding`을 통일하고,
페이지별로 `아이콘 크기`가 다르던 공지 컴포넌트를 일관되게 수정했습니다. (기준: 알림 페이지)
|<img width="250" alt="image" src="https://github.com/user-attachments/assets/9358f554-a4b4-446e-ae03-15d218d1abcf" />  |<img width="250" alt="image" src="https://github.com/user-attachments/assets/1be6227b-8693-463a-958d-a3c7a2b1c9cc" />  |

#1240 [SNO-179] 공지창과 검색창 컴포넌트 padding, 폰트사이즈, 아이콘 크기를 동일한 값으로 수정
